"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const SOURCE_FILES = [
	"head", "ready", "rule_classic", "rule_jaqwi", "rule_crossword",
	"rule_typing", "rule_hunmin", "rule_daneo", "rule_sock", "body", "tail"
].map(name => `Server/lib/Web/lib/kkutu/${name}.js`);
const OUTPUT_FILES = [
	"Server/lib/Web/lib/in_game_kkutu.js",
	"Server/lib/Web/public/js/in_game_kkutu.js",
	"Server/lib/Web/public/js/in_game_kkutu.min.js"
];
const BANNER = "// Generated by tools/build_client.js from Web/lib/kkutu/*.js.\n" +
	"// Edit the split sources and rebuild both served clients.\n\n";

function compileClient(){
	const source = BANNER + SOURCE_FILES.map(relativePath =>
		fs.readFileSync(path.join(root, relativePath), "utf8")
			.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").trimEnd() + "\n"
	).join("\n");
	new vm.Script(source, { filename: "in_game_kkutu.js" });
	return source;
}

function buildClient(options){
	const source = compileClient();
	const stale = OUTPUT_FILES.filter(relativePath => {
		const target = path.join(root, relativePath);
		return !fs.existsSync(target) || fs.readFileSync(target, "utf8") !== source;
	});
	if(options && options.check){
		if(stale.length) throw new Error("Client outputs are stale: " + stale.join(", ") + ". Run node tools/build_client.js.");
	}else{
		stale.forEach(relativePath => fs.writeFileSync(path.join(root, relativePath), source, "utf8"));
	}
	return { source, changed: stale };
}

module.exports = { SOURCE_FILES, OUTPUT_FILES, compileClient, buildClient };

if(require.main === module){
	try{
		const check = process.argv.indexOf("--check") !== -1;
		const result = buildClient({ check });
		console.log(check ? "Client outputs match their sources." : `Built client outputs (${result.changed.length} changed).`);
	}catch(error){
		console.error(error.message);
		process.exitCode = 1;
	}
}
