module.exports = {
	MINC: [
		"ender pearl", "blaze rod", "blaze powder", "eye of ender", "ender eye",
		"ender portal", "nether portal", "diamond sword", "diamond armor", "iron sword",
		"iron armor", "golden apple", "enchanted apple", "totem of undying", "music disc",
		"note block", "redstone torch", "redstone repeater", "redstone comparator", "hopper minecart",
		"chest minecart", "tnt minecart", "powered rail", "detector rail", "activator rail",
		"bamboo raft", "chiseled bookshelf", "decorated pot", "sniffer egg", "trial spawner"
	],
	STA: [
		"battle cruiser", "science vessel", "command center", "orbital command", "planetary fortress",
		"missile turret", "engineering bay", "academy", "machine shop", "control tower",
		"physics lab", "covert ops", "nuclear silo", "spider mine", "nydus canal",
		"ultralisk cavern", "hydralisk den", "defiler mound", "queen nest", "evolution chamber",
		"citadel of adun", "robotics facility", "observatory", "fleet beacon", "arbiter tribunal",
		"shield battery", "dragoon range", "psionic storm", "dark swarm", "irradiate"
	],
	POK: [
		"dragonair", "dragonite", "mew", "mewtwo", "slowbro",
		"scizor", "heracross", "tyranitar", "lugia", "celebi",
		"salamence", "metagross", "rayquaza", "latias", "latios",
		"empoleon", "infernape", "torterra", "lucario", "garchomp",
		"darkrai", "giratina", "reshiram", "zekrom", "greninja",
		"sylveon", "aegislash", "decidueye", "mimikyu", "dragapult",
		"ceruledge", "chien pao", "ting lu", "iron valiant", "walking wake",
		"roaring moon", "great tusk", "mr mime", "mime junior", "type null"
	],
	FORT: [
		"battle royale", "zero build", "rocket launcher", "heavy sniper", "tactical shotgun",
		"combat shotgun", "burst rifle", "drum gun", "suppressed smg", "shield keg",
		"chug splash", "slap juice", "shockwave hammer", "kinetic blade", "business turret",
		"anvil launcher", "junk rift", "impulse grenade", "boogie bomb", "bouncer",
		"launch pad", "supply llama", "pleasant plaza", "shifty shafts", "haunted hills",
		"fatal fields", "lonely lodge", "craggy cliffs", "misty meadows", "mega city"
	],
	VALO: [
		"kill contract", "ultimate orb", "spike rush", "deathmatch", "team deathmatch",
		"swiftplay", "escalation", "premier", "custom game", "headhunter",
		"tour de force", "seekers", "showstopper", "blade storm", "hunter fury",
		"rolling thunder", "neural theft", "resurrection", "nightfall", "rolling smoke",
		"paint shells", "satchel", "toxic screen", "snake bite", "slow orb",
		"barrier orb", "hot hands", "curveball", "paranoia", "dark cover"
	],
	PUBG: [
		"blue zone", "care package", "flare gun", "emergency pickup", "mountain bike",
		"mortar", "blue chip", "blue chip detector", "repair kit", "spike trap",
		"duckbill", "compensator", "extended mag", "quickdraw mag", "cheek pad",
		"holographic sight", "red dot sight", "first aid", "energy drink", "adrenaline syringe",
		"tactical stock", "drone tablet", "jammer pack", "snowmobile", "motor glider",
		"police vest", "military vest", "level three helmet", "ghillie suit", "crowbar"
	],
	APEX: [
		"alternator", "r three zero one", "flatline", "eva eight", "peacekeeper",
		"mastiff", "wingman", "sentinel", "kraber", "longbow",
		"charge rifle", "triple take", "prowler", "havoc", "nemesis",
		"mozambique", "arc star", "thermite grenade", "frag grenade", "heat shield",
		"mobile respawn", "jump tower", "evac tower", "replicator", "crafting materials",
		"gold knockdown", "red armor", "white armor", "shield cell", "phoenix kit"
	],
	OVW: [
		"soldier seventy six", "wrecking ball", "junker queen", "lifeweaver", "doomfist",
		"dva", "reinhardt", "zarya", "echo", "ashe",
		"junkrat", "sojourn railgun", "pulse bomb", "dragonstrike", "dragonblade",
		"nano boost", "sound barrier", "transcendence", "graviton surge", "tactical visor",
		"earthshatter", "self destruct", "death blossom", "whole hog", "kitsune rush",
		"coalescence", "biotic grenade", "sleep dart", "immortality field", "captain amari"
	],
	"450": [
		{ word: "event horizon", definition: "The boundary around a black hole beyond which nothing escapes.", extraThemes: [ "160" ] },
		{ word: "light year", definition: "The distance light travels in one year." },
		{ word: "redshift", definition: "The stretching of light toward longer wavelengths from distant objects.", extraThemes: [ "160" ] },
		{ word: "blueshift", definition: "The shift of light toward shorter wavelengths from approaching objects.", extraThemes: [ "160" ] },
		{ word: "main sequence", definition: "The long stable stage of a star powered by hydrogen fusion.", extraThemes: [ "160" ] },
		{ word: "neutron star", definition: "An extremely dense stellar remnant made mostly of neutrons.", extraThemes: [ "160" ] },
		{ word: "brown dwarf", definition: "An object too small to sustain ordinary hydrogen fusion." },
		{ word: "white dwarf", definition: "A small dense stellar remnant left after a low mass star dies." },
		{ word: "red giant", definition: "A swollen late stage star with a cool outer layer." },
		{ word: "spiral galaxy", definition: "A galaxy with a flat rotating disk and spiral arms." },
		{ word: "elliptical galaxy", definition: "A galaxy with a smooth rounded light distribution." },
		{ word: "irregular galaxy", definition: "A galaxy lacking a clear spiral or elliptical form." },
		{ word: "globular cluster", definition: "A dense spherical collection of old stars." },
		{ word: "open cluster", definition: "A loose group of stars born from the same cloud." },
		{ word: "kuiper belt", definition: "A ring of icy bodies beyond Neptune." },
		{ word: "oort cloud", definition: "A distant spherical reservoir of icy solar system bodies." },
		{ word: "solar wind", definition: "A stream of charged particles flowing outward from the sun.", extraThemes: [ "160" ] },
		{ word: "lunar eclipse", definition: "An eclipse in which Earth blocks sunlight from the moon." },
		{ word: "solar eclipse", definition: "An eclipse in which the moon blocks the sun from view." },
		{ word: "milky way", definition: "The galaxy that contains the solar system." },
		{ word: "local group", definition: "The cluster of galaxies that includes the Milky Way." },
		{ word: "dark matter", definition: "Invisible matter inferred from its gravitational effects.", extraThemes: [ "160" ] },
		{ word: "dark energy", definition: "The unknown component driving the universe's accelerated expansion.", extraThemes: [ "160" ] },
		{ word: "cosmic microwave background", definition: "The faint radiation left from the early universe." },
		{ word: "planetary nebula", definition: "An expanding shell of gas shed by a dying star." },
		{ word: "accretion disk", definition: "A rotating disk of matter spiraling into a massive body.", extraThemes: [ "160" ] },
		{ word: "tidal force", definition: "A difference in gravity that stretches bodies across distance.", extraThemes: [ "160" ] },
		{ word: "space telescope", definition: "A telescope placed above Earth's atmosphere." },
		{ word: "celestial sphere", definition: "An imaginary sphere onto which the sky is projected." },
		{ word: "sidereal day", definition: "The time Earth takes to rotate once relative to distant stars." }
	],
	"160": [
		{ word: "angular momentum", definition: "Rotational momentum conserved in isolated systems." },
		{ word: "potential energy", definition: "Stored energy due to position or configuration." },
		{ word: "kinetic energy", definition: "Energy possessed by motion." },
		{ word: "electric field", definition: "A region in which electric charges feel force." },
		{ word: "magnetic field", definition: "A region in which moving charges or magnets feel force." },
		{ word: "electric potential", definition: "Potential energy per unit charge at a point." },
		{ word: "coulomb law", definition: "The law describing electric force between charges." },
		{ word: "gauss law", definition: "A law relating electric flux to enclosed charge." },
		{ word: "faraday law", definition: "The law describing how changing magnetic fields induce voltage." },
		{ word: "inductance", definition: "The tendency of a circuit to oppose changes in current." },
		{ word: "capacitance", definition: "The ability to store electric charge." },
		{ word: "harmonic motion", definition: "Repeated oscillation around equilibrium with restoring force." },
		{ word: "centrifugal force", definition: "An apparent outward force in a rotating frame." },
		{ word: "wave packet", definition: "A localized combination of waves." },
		{ word: "phase velocity", definition: "The rate at which a wave phase travels." },
		{ word: "group velocity", definition: "The speed at which a wave envelope moves." },
		{ word: "nuclear fusion", definition: "The joining of light nuclei with energy release." },
		{ word: "nuclear fission", definition: "The splitting of a heavy nucleus into smaller parts." },
		{ word: "half life", definition: "The time needed for half of a radioactive sample to decay." },
		{ word: "standard model", definition: "The theory describing fundamental particles and forces except gravity." },
		{ word: "boson", definition: "A particle that can share a quantum state with others." },
		{ word: "fermion", definition: "A particle that obeys the exclusion principle." },
		{ word: "higgs boson", definition: "The particle associated with the Higgs field." },
		{ word: "planck constant", definition: "The fundamental constant linking energy and frequency." },
		{ word: "schrodinger equation", definition: "The equation governing the evolution of quantum states." },
		{ word: "uncertainty principle", definition: "The limit on simultaneous knowledge of certain paired quantities." },
		{ word: "special relativity", definition: "The theory of space and time for inertial frames." },
		{ word: "general relativity", definition: "The theory describing gravity as spacetime curvature." },
		{ word: "frame of reference", definition: "The perspective from which motion is measured." },
		{ word: "conservation law", definition: "A rule that keeps a physical quantity constant in a closed system." }
	],
	"490": [
		{ word: "binary tree", definition: "A tree data structure in which nodes have at most two children.", extraThemes: [ "240" ] },
		{ word: "linked list", definition: "A sequence of nodes connected by references." },
		{ word: "priority queue", definition: "A structure that removes items by priority rather than insertion order." },
		{ word: "depth first search", definition: "A graph traversal that explores branches deeply before backtracking.", extraThemes: [ "240" ] },
		{ word: "breadth first search", definition: "A graph traversal that explores neighbors level by level.", extraThemes: [ "240" ] },
		{ word: "dynamic programming", definition: "A method that solves problems through stored subproblem results.", extraThemes: [ "240" ] },
		{ word: "greedy algorithm", definition: "A method that repeatedly takes the locally best choice.", extraThemes: [ "240" ] },
		{ word: "time complexity", definition: "The rate at which running time grows with input size.", extraThemes: [ "240" ] },
		{ word: "space complexity", definition: "The rate at which memory usage grows with input size.", extraThemes: [ "240" ] },
		{ word: "big o notation", definition: "A notation describing upper growth bounds of algorithms.", extraThemes: [ "240" ] },
		{ word: "finite automaton", definition: "A simple abstract machine with a finite number of states." },
		{ word: "context free grammar", definition: "A grammar whose productions replace one nonterminal at a time." },
		{ word: "regular expression", definition: "A pattern language used to match text." },
		{ word: "sql injection", definition: "An attack that exploits unsafe database query construction." },
		{ word: "public key", definition: "The openly shared part of an asymmetric cryptographic pair." },
		{ word: "private key", definition: "The secret part of an asymmetric cryptographic pair." },
		{ word: "version control", definition: "A system that tracks changes to files over time." },
		{ word: "distributed system", definition: "A system whose components run on multiple networked machines." },
		{ word: "load balancer", definition: "A service that spreads work across multiple servers." },
		{ word: "garbage collection", definition: "Automatic recovery of memory no longer in use." },
		{ word: "object oriented programming", definition: "A programming style organized around objects and classes." },
		{ word: "functional programming", definition: "A programming style centered on functions and immutable data." },
		{ word: "command line", definition: "A text based interface for running programs and commands." },
		{ word: "computer network", definition: "A connected system of computers that exchange data." },
		{ word: "artificial intelligence", definition: "The field of making machines perform tasks associated with intelligence.", extraThemes: [ "DSCI" ] },
		{ word: "neural network", definition: "A layered model inspired by connected units in brains.", extraThemes: [ "DSCI" ] },
		{ word: "search engine", definition: "A system that indexes and retrieves information." },
		{ word: "query optimizer", definition: "A database component that chooses efficient execution plans." },
		{ word: "state machine", definition: "A model that changes behavior according to state." },
		{ word: "memory leak", definition: "A bug that fails to release unneeded memory." }
	],
	"240": [
		{ word: "number theory", definition: "The study of integers and their properties." },
		{ word: "real analysis", definition: "The rigorous study of real valued functions and limits." },
		{ word: "complex analysis", definition: "The study of functions of complex variables." },
		{ word: "linear algebra", definition: "The mathematics of vectors, matrices, and linear maps." },
		{ word: "abstract algebra", definition: "The study of algebraic structures such as groups and rings." },
		{ word: "graph theory", definition: "The study of networks of vertices and edges." },
		{ word: "set theory", definition: "The study of sets and their relationships." },
		{ word: "measure theory", definition: "The mathematics of generalized size and integration." },
		{ word: "game theory", definition: "The mathematics of strategic interaction." },
		{ word: "partial derivative", definition: "A derivative with respect to one variable while others stay fixed." },
		{ word: "differential equation", definition: "An equation involving a function and its derivatives." },
		{ word: "ordinary differential equation", definition: "A differential equation involving one independent variable." },
		{ word: "prime number", definition: "An integer greater than one with exactly two positive divisors." },
		{ word: "composite number", definition: "An integer greater than one that has more than two divisors." },
		{ word: "greatest common divisor", definition: "The largest integer that divides two integers exactly." },
		{ word: "least common multiple", definition: "The smallest positive integer divisible by given integers." },
		{ word: "modular arithmetic", definition: "Arithmetic performed with wraparound under a modulus." },
		{ word: "pascal triangle", definition: "A triangular array of binomial coefficients." },
		{ word: "golden ratio", definition: "A famous irrational ratio appearing in geometry and art." },
		{ word: "fibonacci sequence", definition: "A sequence in which each term is the sum of the previous two." },
		{ word: "normal distribution", definition: "A symmetric bell shaped probability distribution.", extraThemes: [ "DSCI" ] },
		{ word: "expected value", definition: "The average outcome weighted by probabilities.", extraThemes: [ "DSCI" ] },
		{ word: "standard deviation", definition: "A measure of how spread out values are.", extraThemes: [ "DSCI" ] },
		{ word: "sample space", definition: "The set of all possible outcomes in a random experiment.", extraThemes: [ "DSCI" ] },
		{ word: "null hypothesis", definition: "The default statement tested in statistics.", extraThemes: [ "DSCI" ] },
		{ word: "p value", definition: "The probability of observing data this extreme under the null hypothesis.", extraThemes: [ "DSCI" ] },
		{ word: "confidence interval", definition: "A range likely to contain a population value.", extraThemes: [ "DSCI" ] },
		{ word: "markov chain", definition: "A stochastic process whose next state depends only on the current state.", extraThemes: [ "DSCI" ] },
		{ word: "proof by induction", definition: "A proof method that establishes a base case and inductive step." },
		{ word: "proof by contradiction", definition: "A proof method that assumes the opposite and derives impossibility." }
	],
	DSCI: [
		{ word: "decision tree", definition: "A predictive model that splits data by decision rules." },
		{ word: "random forest", definition: "An ensemble of decision trees used for prediction." },
		{ word: "gradient boosting", definition: "An ensemble method that improves models stage by stage." },
		{ word: "logistic regression", definition: "A probabilistic model used for classification." },
		{ word: "linear regression", definition: "A model that predicts a numeric outcome with a linear relation." },
		{ word: "confusion matrix", definition: "A table that compares predicted and true classes." },
		{ word: "precision score", definition: "The share of positive predictions that are correct." },
		{ word: "recall score", definition: "The share of true positives recovered by a model." },
		{ word: "f one score", definition: "The harmonic mean of precision and recall." },
		{ word: "roc curve", definition: "A curve that compares true positive and false positive rates." },
		{ word: "area under curve", definition: "A summary measure of classifier ranking performance." },
		{ word: "feature selection", definition: "The process of choosing useful variables for modeling." },
		{ word: "feature scaling", definition: "The rescaling of variables to comparable ranges." },
		{ word: "principal component analysis", definition: "A method that reduces dimensions by finding major directions of variation." },
		{ word: "natural language processing", definition: "The analysis and generation of human language by computers.", extraThemes: [ "490", "310" ] },
		{ word: "computer vision", definition: "The field of extracting information from images and video." },
		{ word: "recommendation system", definition: "A model that suggests items to users." },
		{ word: "anomaly detection", definition: "The task of finding unusual observations." },
		{ word: "survival analysis", definition: "Statistical analysis of time until an event occurs." },
		{ word: "causal inference", definition: "Methods for estimating cause and effect from data." },
		{ word: "data wrangling", definition: "The cleaning and reshaping of raw data." },
		{ word: "label encoding", definition: "The conversion of categories into numeric labels." },
		{ word: "one hot encoding", definition: "The representation of categories with binary indicator columns." },
		{ word: "class imbalance", definition: "A condition in which some categories are much rarer than others." },
		{ word: "baseline model", definition: "A simple reference model used for comparison." },
		{ word: "hyperparameter tuning", definition: "The search for the best training settings." },
		{ word: "data leakage", definition: "A modeling flaw caused by using information unavailable at prediction time." },
		{ word: "holdout set", definition: "A reserved dataset used only for final evaluation." },
		{ word: "a b test", definition: "An experiment that compares two variants on real outcomes." },
		{ word: "business intelligence", definition: "The practice of turning data into decisions and reports." }
	],
	"150": [
		{ word: "the republic", definition: "Plato's classical dialogue about justice, society, and the ideal state." },
		{ word: "metamorphoses", definition: "Ovid's classical poem of mythic transformations." },
		{ word: "the canterbury tales", definition: "Chaucer's major Middle English collection of pilgrimage stories." },
		{ word: "the faerie queene", definition: "Spenser's epic allegorical poem of virtue and chivalry." },
		{ word: "paradise lost", definition: "Milton's epic poem about the Fall of Man." },
		{ word: "gulliver travels", definition: "Swift's satirical novel of strange voyages and societies." },
		{ word: "candide", definition: "Voltaire's satirical novella mocking optimism." },
		{ word: "the red and the black", definition: "Stendhal's novel of ambition and social climbing in France." },
		{ word: "fathers and sons", definition: "Turgenev's novel of generational conflict and nihilism." },
		{ word: "dead souls", definition: "Gogol's satirical Russian novel about greed and corruption." },
		{ word: "the trial", definition: "Kafka's novel about accusation, bureaucracy, and alienation." },
		{ word: "the castle", definition: "Kafka's unfinished novel about authority and exclusion." },
		{ word: "ulysses", definition: "Joyce's modernist novel set over a single day in Dublin." },
		{ word: "mrs dalloway", definition: "Woolf's modernist novel centered on one day in London." },
		{ word: "the sound and the fury", definition: "Faulkner's modernist novel of family decline and fractured narration." },
		{ word: "in search of lost time", definition: "Proust's monumental novel cycle of memory and society." },
		{ word: "the plague", definition: "Camus's novel about disease, absurdity, and solidarity." },
		{ word: "the stranger", definition: "Camus's novel about alienation and moral indifference." },
		{ word: "doctor zhivago", definition: "Pasternak's novel of love and survival during upheaval in Russia." },
		{ word: "the master and margarita", definition: "Bulgakov's celebrated novel blending satire, fantasy, and faith." },
		{ word: "things fall apart", definition: "Achebe's classic novel about Igbo society and colonial disruption." },
		{ word: "the name of the rose", definition: "Eco's historical mystery novel set in a medieval monastery." },
		{ word: "the remains of the day", definition: "Ishiguro's Booker-winning novel about memory and duty." },
		{ word: "the road", definition: "McCarthy's Pulitzer-winning novel of survival after catastrophe." },
		{ word: "the goldfinch", definition: "Tartt's Pulitzer-winning novel about loss, art, and obsession." },
		{ word: "wolf hall", definition: "Mantel's Booker-winning novel about Thomas Cromwell and Tudor power." },
		{ word: "the overstory", definition: "Powers's Pulitzer-winning novel about human lives and trees." },
		{ word: "disgrace", definition: "Coetzee's Booker-winning novel about power and post apartheid South Africa." },
		{ word: "love in the time of cholera", definition: "Garcia Marquez's novel of love, age, and memory." },
		{ word: "the brothers karamazov", definition: "Dostoevsky's philosophical novel about faith, doubt, and family." }
	],
	"30": [
		{ word: "gross domestic product", definition: "The total output of goods and services produced in an economy." },
		{ word: "consumer price index", definition: "An index tracking changes in the prices paid by consumers." },
		{ word: "interest rate", definition: "The price charged for borrowing money." },
		{ word: "exchange rate", definition: "The price of one currency in terms of another." },
		{ word: "capital gains", definition: "Profits earned from selling assets above purchase price." },
		{ word: "venture capital", definition: "Investment in young companies with high growth potential." },
		{ word: "private equity", definition: "Ownership investment in companies not traded publicly." },
		{ word: "labor market", definition: "The market in which workers and employers interact." },
		{ word: "opportunity cost", definition: "The value of the best alternative forgone." },
		{ word: "comparative advantage", definition: "The ability to produce at lower opportunity cost than others." },
		{ word: "price elasticity", definition: "The responsiveness of demand or supply to price changes." },
		{ word: "purchasing power", definition: "The amount of goods or services money can buy." },
		{ word: "trade deficit", definition: "A condition in which imports exceed exports." },
		{ word: "trade surplus", definition: "A condition in which exports exceed imports." },
		{ word: "current account", definition: "A record of trade, income, and transfers with the rest of the world." },
		{ word: "balance sheet", definition: "A statement of assets, liabilities, and equity." },
		{ word: "income statement", definition: "A report of revenue, costs, and profit." },
		{ word: "cash flow", definition: "The movement of money into and out of a business." },
		{ word: "market failure", definition: "A situation in which markets allocate resources inefficiently." },
		{ word: "externality", definition: "A side effect of activity imposed on others without market pricing." },
		{ word: "marginal cost", definition: "The cost of producing one additional unit." },
		{ word: "marginal revenue", definition: "The added revenue from selling one additional unit." },
		{ word: "consumer surplus", definition: "The gap between what consumers pay and what they were willing to pay." },
		{ word: "producer surplus", definition: "The gap between market price and producers' minimum acceptable price." },
		{ word: "inflation target", definition: "A central bank's intended inflation rate." },
		{ word: "yield curve", definition: "A graph of interest rates across bond maturities." },
		{ word: "credit rating", definition: "An assessment of a borrower's default risk." },
		{ word: "quantitative easing", definition: "Central bank asset purchases used to support the economy." },
		{ word: "human capital", definition: "The skills and knowledge that raise worker productivity." },
		{ word: "supply side", definition: "Economic thinking focused on production incentives and capacity." }
	],
	"310": [
		{ word: "historical linguistics", definition: "The study of how languages change over time." },
		{ word: "comparative linguistics", definition: "The comparison of languages to uncover relationships." },
		{ word: "applied linguistics", definition: "The use of linguistic knowledge in practical settings." },
		{ word: "computational linguistics", definition: "The study of language with computational methods.", extraThemes: [ "490", "DSCI" ] },
		{ word: "language family", definition: "A group of languages descended from a common ancestor." },
		{ word: "language isolate", definition: "A language with no known genealogical relatives." },
		{ word: "speech act", definition: "An utterance understood as an action in context." },
		{ word: "deixis", definition: "Language whose meaning depends on speaker, place, or time." },
		{ word: "collocation", definition: "A pair or group of words that frequently occur together." },
		{ word: "idiom", definition: "A fixed expression whose meaning is not literal." },
		{ word: "dialect", definition: "A regional or social variety of a language." },
		{ word: "accent", definition: "A distinct manner of pronunciation." },
		{ word: "loanword", definition: "A word borrowed from another language." },
		{ word: "calque", definition: "A loan translation modeled on a foreign expression." },
		{ word: "stress pattern", definition: "The arrangement of prominence across syllables." },
		{ word: "tone language", definition: "A language in which pitch distinguishes lexical meaning." },
		{ word: "case marking", definition: "The morphological marking of grammatical roles." },
		{ word: "word order", definition: "The arrangement of elements in a clause or sentence." },
		{ word: "ergative", definition: "A grammatical alignment grouping subjects of intransitives with objects of transitives." },
		{ word: "digraph", definition: "A pair of letters representing one sound." },
		{ word: "trigraph", definition: "A group of three letters representing one sound." },
		{ word: "vowel harmony", definition: "A process in which vowels in a word share features." },
		{ word: "consonant cluster", definition: "A sequence of adjacent consonants in a syllable or word." },
		{ word: "semantic shift", definition: "A historical change in the meaning of a word." },
		{ word: "language contact", definition: "Interaction between languages that leads to influence or change." }
	],
	"350": [
		{ word: "pick and roll", definition: "A basketball play using a screen followed by a cut to space." },
		{ word: "triple double", definition: "A basketball game in which a player reaches double digits in three categories." },
		{ word: "clean sheet", definition: "A game in which a team concedes no goals." },
		{ word: "golden boot", definition: "An award for a top goal scorer." },
		{ word: "red card", definition: "A dismissal penalty in soccer." },
		{ word: "yellow card", definition: "A caution issued by a referee in soccer." },
		{ word: "corner kick", definition: "A restart awarded when defenders last touch the ball over the goal line." },
		{ word: "free kick", definition: "A restart awarded after certain fouls." },
		{ word: "home run derby", definition: "A contest focused on hitting the most home runs." },
		{ word: "grand slam", definition: "A term for four majors in tennis or a bases loaded home run in baseball." },
		{ word: "walk off", definition: "A winning score in the final turn of the home team." },
		{ word: "inning", definition: "A division of play in baseball or softball." },
		{ word: "power play", definition: "A period with a numerical advantage after a penalty in hockey." },
		{ word: "hat trick hero", definition: "A player who scores three times in one match." },
		{ word: "false nine", definition: "A forward who drops into midfield rather than staying high." },
		{ word: "high press", definition: "An aggressive tactic that pressures opponents near their own goal." },
		{ word: "counter attack", definition: "A rapid attack launched after winning the ball back." },
		{ word: "field goal", definition: "A made shot in basketball or a scoring kick in American football." },
		{ word: "touchline", definition: "The sideline marking the boundary of a field." },
		{ word: "pace bowler", definition: "A cricket bowler who relies on speed." },
		{ word: "spin bowler", definition: "A cricket bowler who relies on turn off the pitch." },
		{ word: "pole vault", definition: "A track and field event using a pole to clear a bar." },
		{ word: "high jump", definition: "A field event in which athletes jump over a horizontal bar." },
		{ word: "long jump", definition: "A field event measuring horizontal jumping distance." },
		{ word: "shot put", definition: "A field event in which a heavy ball is thrown for distance." }
	],
	"1001": [
		{ word: "saudi arabia", definition: "A large country on the Arabian Peninsula.", extraThemes: [ "e15" ] },
		{ word: "costa rica", definition: "A Central American country between Nicaragua and Panama.", extraThemes: [ "e15" ] },
		{ word: "el salvador", definition: "The smallest and most densely populated country in Central America.", extraThemes: [ "e15" ] },
		{ word: "guatemala", definition: "A Central American country with a strong Mayan heritage.", extraThemes: [ "e15" ] },
		{ word: "honduras", definition: "A Central American country with coastlines on two seas.", extraThemes: [ "e15" ] },
		{ word: "nicaragua", definition: "A Central American country with large lakes and volcanoes.", extraThemes: [ "e15" ] },
		{ word: "panama", definition: "A Central American country linking North and South America.", extraThemes: [ "e15" ] },
		{ word: "cuba", definition: "A Caribbean island country west of Haiti.", extraThemes: [ "e15" ] },
		{ word: "jamaica", definition: "A Caribbean island country known for reggae and sprinting.", extraThemes: [ "e15" ] },
		{ word: "haiti", definition: "A Caribbean country occupying the western part of Hispaniola.", extraThemes: [ "e15" ] },
		{ word: "dominican republic", definition: "A Caribbean country occupying most of Hispaniola.", extraThemes: [ "e15" ] },
		{ word: "czech republic", definition: "A central European country also known as Czechia.", extraThemes: [ "e15" ] },
		{ word: "slovakia", definition: "A central European country east of the Czech Republic.", extraThemes: [ "e15" ] },
		{ word: "slovenia", definition: "A central European country on the Adriatic region.", extraThemes: [ "e15" ] },
		{ word: "croatia", definition: "A country on the Adriatic Sea in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "serbia", definition: "A Balkan country in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "romania", definition: "An eastern European country on the Black Sea.", extraThemes: [ "e15" ] },
		{ word: "bulgaria", definition: "A southeastern European country on the Black Sea.", extraThemes: [ "e15" ] },
		{ word: "hungary", definition: "A landlocked country in central Europe.", extraThemes: [ "e15" ] },
		{ word: "belgium", definition: "A western European country known for Brussels and multilingual regions.", extraThemes: [ "e15" ] },
		{ word: "netherlands", definition: "A low lying western European country known for Amsterdam.", extraThemes: [ "e15" ] },
		{ word: "denmark", definition: "A Nordic country linking continental Europe and Scandinavia.", extraThemes: [ "e15" ] },
		{ word: "norway", definition: "A Nordic country known for mountains and fjords.", extraThemes: [ "e15" ] },
		{ word: "sweden", definition: "A Nordic country in Scandinavia.", extraThemes: [ "e15" ] },
		{ word: "finland", definition: "A Nordic country between Sweden and Russia.", extraThemes: [ "e15" ] },
		{ word: "iceland", definition: "A Nordic island country in the North Atlantic.", extraThemes: [ "e15" ] },
		{ word: "malaysia", definition: "A Southeast Asian country split between peninsula and island territories.", extraThemes: [ "e15" ] },
		{ word: "singapore", definition: "A city state in Southeast Asia with a major port economy.", extraThemes: [ "e15" ] },
		{ word: "taiwan", definition: "An island polity in East Asia.", extraThemes: [ "e15" ] },
		{ word: "mongolia", definition: "A landlocked East Asian country between Russia and China.", extraThemes: [ "e15" ] }
	],
	NBAP: [
		{ word: "hakeem olajuwon", definition: "Hakeem Olajuwon debuted in 1984 and led Houston to two NBA titles." },
		{ word: "isiah thomas", definition: "Isiah Thomas debuted in 1981 and led Detroit's Bad Boys era to two championships." },
		{ word: "john stockton", definition: "John Stockton debuted in 1984 and became the NBA's all time assists leader." },
		{ word: "karl malone", definition: "Karl Malone debuted in 1985 and became one of the greatest scoring forwards ever." },
		{ word: "gary payton", definition: "Gary Payton debuted in 1990 and became a champion and elite defensive guard." },
		{ word: "jason kidd", definition: "Jason Kidd debuted in 1994 and became one of the top passing guards in NBA history." },
		{ word: "steve nash", definition: "Steve Nash debuted in 1996 and won back to back MVP awards." },
		{ word: "dirk nowitzki", definition: "Dirk Nowitzki debuted in 1998 and led Dallas to the 2011 title." },
		{ word: "amare stoudemire", definition: "Amare Stoudemire debuted in 2002 and became a dominant scoring big man." },
		{ word: "gilbert arenas", definition: "Gilbert Arenas debuted in 2001 and became an explosive scoring guard." },
		{ word: "joe johnson", definition: "Joe Johnson debuted in 2001 and became a seven time NBA All Star." },
		{ word: "deron williams", definition: "Deron Williams debuted in 2005 and became one of the league's best guards in his prime." },
		{ word: "joakim noah", definition: "Joakim Noah debuted in 2007 and won Defensive Player of the Year in 2014." },
		{ word: "lamarcus aldridge", definition: "LaMarcus Aldridge debuted in 2006 and became a multiple time All NBA big man." },
		{ word: "kevin love", definition: "Kevin Love debuted in 2008 and won an NBA title with Cleveland." },
		{ word: "demarcus cousins", definition: "DeMarcus Cousins debuted in 2010 and became one of the era's most skilled centers." },
		{ word: "gordon hayward", definition: "Gordon Hayward debuted in 2010 and became an All Star wing." },
		{ word: "isaiah thomas", definition: "Isaiah Thomas debuted in 2011 and became an All NBA guard for Boston." },
		{ word: "brandon ingram", definition: "Brandon Ingram debuted in 2016 and became an All Star forward with New Orleans." },
		{ word: "dejounte murray", definition: "Dejounte Murray debuted in 2016 and developed into an All Star two way guard." },
		{ word: "darius garland", definition: "Darius Garland debuted in 2019 and became Cleveland's lead playmaker." },
		{ word: "tyrese maxey", definition: "Tyrese Maxey debuted in 2020 and became a breakout scoring guard for Philadelphia." },
		{ word: "desmond bane", definition: "Desmond Bane debuted in 2020 and became a key shooter for Memphis." },
		{ word: "jarrett allen", definition: "Jarrett Allen debuted in 2017 and became an All Star rim protecting center." },
		{ word: "mikal bridges", definition: "Mikal Bridges debuted in 2018 and became known for durability and wing defense." },
		{ word: "og anunoby", definition: "OG Anunoby debuted in 2017 and became one of the league's strongest defensive wings." },
		{ word: "fred vanvleet", definition: "Fred VanVleet debuted in 2016 and won the 2019 title with Toronto." },
		{ word: "kyle lowry", definition: "Kyle Lowry debuted in 2006 and became the lead guard of Toronto's title team." },
		{ word: "mike conley", definition: "Mike Conley debuted in 2007 and became a respected veteran point guard." },
		{ word: "andre iguodala", definition: "Andre Iguodala debuted in 2004 and won Finals MVP in 2015." }
	],
	SOCP: [
		{ word: "wayne rooney", definition: "Wayne Rooney debuted in 2002 and became Manchester United's former record scorer." },
		{ word: "david beckham", definition: "David Beckham debuted in 1992 and became one of football's most famous crossers and set piece takers." },
		{ word: "thierry henry", definition: "Thierry Henry debuted in 1994 and became Arsenal's record scorer." },
		{ word: "robin van persie", definition: "Robin van Persie debuted in 2001 and won the Premier League Golden Boot twice." },
		{ word: "wayne bridge", definition: "Wayne Bridge debuted in 1998 and spent many years in the Premier League." },
		{ word: "andrea pirlo", definition: "Andrea Pirlo debuted in 1995 and became one of football's iconic deep lying playmakers." },
		{ word: "gennaro gattuso", definition: "Gennaro Gattuso debuted in 1995 and became a World Cup winning midfield enforcer." },
		{ word: "alessandro del piero", definition: "Alessandro Del Piero debuted in 1991 and became a Juventus legend." },
		{ word: "francesco totti", definition: "Francesco Totti debuted in 1992 and spent his career as Roma's iconic captain." },
		{ word: "paolo rossi", definition: "Paolo Rossi debuted in 1973 and led Italy's scoring at the 1982 World Cup." },
		{ word: "ruud van nistelrooy", definition: "Ruud van Nistelrooy debuted in 1993 and became one of Europe's top penalty box finishers." },
		{ word: "arjen robben", definition: "Arjen Robben debuted in 2000 and became famous for cutting inside from the wing." },
		{ word: "clarence seedorf", definition: "Clarence Seedorf debuted in 1992 and won the Champions League with three clubs." },
		{ word: "edwin van der sar", definition: "Edwin van der Sar debuted in 1990 and became one of the era's top goalkeepers." },
		{ word: "robinho", definition: "Robinho debuted in 2002 and became a celebrated Brazilian attacker." },
		{ word: "kaka", definition: "Kaka debuted in 2001 and won the 2007 Ballon d'Or." },
		{ word: "cafu", definition: "Cafu debuted in 1989 and won two World Cups with Brazil." },
		{ word: "thiago silva", definition: "Thiago Silva debuted in 2002 and became one of the era's elite defenders." },
		{ word: "virgil van dijk", definition: "Virgil van Dijk debuted in 2011 and became a leading defender for Liverpool and the Netherlands." },
		{ word: "sergio ramos", definition: "Sergio Ramos debuted in 2003 and won major titles for Real Madrid and Spain." },
		{ word: "gerard pique", definition: "Gerard Pique debuted in 2004 and won major titles for Barcelona and Spain." },
		{ word: "carles puyol", definition: "Carles Puyol debuted in 1999 and captained Barcelona through a trophy rich era." },
		{ word: "manuel neuer", definition: "Manuel Neuer debuted in 2006 and became one of the defining goalkeepers of modern football." },
		{ word: "philipp lahm", definition: "Philipp Lahm debuted in 2002 and captained Germany to the 2014 World Cup." },
		{ word: "bastian schweinsteiger", definition: "Bastian Schweinsteiger debuted in 2002 and starred for Germany and Bayern Munich." },
		{ word: "mesut ozil", definition: "Mesut Ozil debuted in 2006 and became known for elite playmaking vision." },
		{ word: "raheem sterling", definition: "Raheem Sterling debuted in 2012 and became a key winger for club and country." },
		{ word: "edinson cavani", definition: "Edinson Cavani debuted in 2005 and became one of Uruguay's great strikers." },
		{ word: "angel di maria", definition: "Angel Di Maria debuted in 2005 and won major club titles and the World Cup with Argentina." },
		{ word: "lautaro martinez", definition: "Lautaro Martinez debuted in 2015 and became a leading striker for Inter and Argentina." }
	],
	"410": [
		{ word: "theology", definition: "The study of the nature of the divine and religious belief." },
		{ word: "monotheism", definition: "Belief in one god." },
		{ word: "polytheism", definition: "Belief in many gods." },
		{ word: "pantheism", definition: "The view that divinity and the universe are identical." },
		{ word: "pilgrimage", definition: "A journey undertaken for religious devotion." },
		{ word: "sacrament", definition: "A sacred rite regarded as a channel of grace." },
		{ word: "scripture", definition: "Sacred writings of a religious tradition." },
		{ word: "canon law", definition: "The body of rules governing a religious community." },
		{ word: "monk", definition: "A man devoted to religious life in a monastery." },
		{ word: "nun", definition: "A woman devoted to religious life in a convent or monastery." },
		{ word: "abbey", definition: "A religious house governed by an abbot or abbess." },
		{ word: "reincarnation", definition: "Belief that a soul is reborn in another life." },
		{ word: "karma", definition: "A moral principle linking actions to later consequences." },
		{ word: "nirvana", definition: "A state of liberation from suffering in Buddhist thought." },
		{ word: "moksha", definition: "Liberation from the cycle of rebirth in Indian religions." },
		{ word: "iconoclasm", definition: "The rejection or destruction of religious images." },
		{ word: "blasphemy", definition: "Speech or action considered insulting to the sacred." },
		{ word: "intercession", definition: "Prayer or action made on behalf of another." },
		{ word: "liturgy", definition: "The set form of public religious worship." },
		{ word: "hymn", definition: "A religious song of praise or devotion." },
		{ word: "creed", definition: "A formal statement of religious belief." },
		{ word: "exorcism", definition: "A ritual meant to expel an evil spirit." },
		{ word: "asceticism", definition: "Severe self discipline often practiced for spiritual purposes." },
		{ word: "sect", definition: "A subgroup within a broader religious tradition." },
		{ word: "doctrine", definition: "A principle or teaching held by a religion." }
	],
	"100": [
		{ word: "artillery", definition: "Large caliber weapons used to fire projectiles over distance." },
		{ word: "destroyer", definition: "A fast maneuverable warship used for escort and attack." },
		{ word: "frigate", definition: "A medium sized warship often used for escort duties." },
		{ word: "submarine", definition: "A naval vessel capable of operating underwater." },
		{ word: "battleship", definition: "A heavily armed and armored capital warship." },
		{ word: "carrier strike group", definition: "A naval force built around an aircraft carrier." },
		{ word: "infantry", definition: "Soldiers who fight mainly on foot." },
		{ word: "paratrooper", definition: "A soldier trained to enter combat by parachute." },
		{ word: "artillery battery", definition: "A unit composed of guns, howitzers, or rocket launchers." },
		{ word: "ballistic missile", definition: "A missile that follows a ballistic flight path." },
		{ word: "cruise missile", definition: "A guided missile that flies within the atmosphere to its target." },
		{ word: "anti aircraft", definition: "Designed to defend against aircraft." },
		{ word: "anti tank", definition: "Designed to destroy armored vehicles." },
		{ word: "camouflage", definition: "Concealment achieved by blending with surroundings." },
		{ word: "logistics", definition: "The organization of supply, transport, and support for forces." },
		{ word: "supply line", definition: "A route used to move troops, food, fuel, and ammunition." },
		{ word: "reconnaissance", definition: "Information gathering about enemy forces or terrain." },
		{ word: "ceasefire", definition: "An agreed temporary stop to fighting." },
		{ word: "demilitarized zone", definition: "An area where military forces and installations are prohibited." },
		{ word: "air defense", definition: "Systems and tactics used to protect against aerial attack." },
		{ word: "amphibious assault", definition: "An attack launched from sea onto land." },
		{ word: "combined arms", definition: "The coordinated use of different military branches and weapons." },
		{ word: "rules of war", definition: "Norms and laws limiting conduct in armed conflict." },
		{ word: "strategic bombing", definition: "Air attacks aimed at an opponent's broader war capacity." },
		{ word: "guerrilla warfare", definition: "Irregular fighting by small groups using mobility and surprise." }
	],
	"370": [
		{ word: "cardiology", definition: "The branch of medicine dealing with the heart." },
		{ word: "oncology", definition: "The branch of medicine dealing with cancer." },
		{ word: "neurology", definition: "The branch of medicine dealing with the nervous system." },
		{ word: "immunology", definition: "The study of the immune system and immune responses." },
		{ word: "pathology", definition: "The study of disease and its causes." },
		{ word: "anatomy", definition: "The study of bodily structure." },
		{ word: "physiology", definition: "The study of how living systems function." },
		{ word: "epidemiology", definition: "The study of the distribution of disease in populations." },
		{ word: "prognosis", definition: "A forecast of the likely course of a disease." },
		{ word: "diagnosis", definition: "The identification of a disease or condition." },
		{ word: "symptom", definition: "A sign or experience that indicates disease." },
		{ word: "syndrome", definition: "A set of symptoms that tend to occur together." },
		{ word: "sepsis", definition: "A dangerous bodywide response to infection." },
		{ word: "anemia", definition: "A condition involving reduced oxygen carrying capacity of blood." },
		{ word: "hypoxia", definition: "A shortage of oxygen in tissue." },
		{ word: "biopsy", definition: "The removal of tissue for diagnostic examination." },
		{ word: "ultrasound", definition: "Imaging that uses high frequency sound waves." },
		{ word: "mri scan", definition: "Imaging that uses magnetic fields and radio waves." },
		{ word: "ct scan", definition: "Cross sectional imaging produced with x rays." },
		{ word: "ventilator", definition: "A machine that supports or replaces breathing." },
		{ word: "antibiotic resistance", definition: "The ability of microbes to survive drugs meant to kill them." },
		{ word: "blood pressure", definition: "The pressure of circulating blood on vessel walls." },
		{ word: "heart failure", definition: "A condition in which the heart cannot pump effectively." },
		{ word: "stroke", definition: "Sudden brain injury caused by interrupted or leaking blood flow." },
		{ word: "myocardial infarction", definition: "The medical term for a heart attack." }
	]
};
