module.exports = {
	MINC: [
		"steve", "alex", "zombie", "skeleton", "creaking",
		"iron golem", "snow golem", "ender chest", "brewing stand", "blast furnace",
		"smoker", "cartography table", "smithing table", "respawn anchor", "lodestone",
		"ancient debris", "dragon egg", "bastion remnant", "nether fortress", "end city",
		"trial chamber", "breeze", "mace", "sculk sensor", "soul sand",
		"trident", "crossbow", "spyglass", "jukebox", "goat horn"
	],
	STA: [
		"jim raynor", "sarah kerrigan", "zeratul", "tassadar", "artanis",
		"stukov", "scv", "probe", "drone", "siege tank",
		"science vessel", "command center", "barracks", "factory", "starport",
		"hatchery", "lair", "hive", "spawning pool", "spire",
		"nexus", "pylon", "photon cannon", "stargate", "cybernetics core",
		"arbiter", "observer", "shuttle", "scourge", "guardian"
	],
	POK: [
		"pokeball", "masterball", "ultraball", "rarecandy", "thunderstone",
		"moonstone", "charmeleon", "wartortle", "ivysaur", "alakazam",
		"machamp", "gyarados", "ditto", "vaporeon", "jolteon",
		"flareon", "articuno", "zapdos", "moltres", "suicune",
		"entei", "raikou", "gardevoir", "sceptile", "blaziken",
		"swampert", "jirachi", "darkrai", "shaymin", "snivy",
		"tepig", "oshawott", "zoroark", "hydreigon", "genesect",
		"chesnaught", "delphox", "decidueye", "incineroar", "primarina",
		"zacian", "zamazenta", "miraidon", "koraidon", "ceruledge"
	],
	FORT: [
		"jonesy", "peely", "fishstick", "meowscles", "sniper rifle",
		"pump shotgun", "assault rifle", "medkit", "minis", "shockwave grenade",
		"rocket ram", "grappler", "campfire", "slurpfish", "storm surge",
		"cuddle team leader", "frenzy fields", "salty springs", "lazy lake", "retail row",
		"greasy grove", "sweaty sands", "polar peak", "the agency", "scar"
	],
	VALO: [
		"raze", "deadlock", "vandal", "phantom", "operator",
		"sheriff", "spectre", "bulldog", "judge", "outlaw",
		"stinger", "marshal", "guardian", "classic", "shorty",
		"frenzy", "ares", "odin", "icebox", "pearl",
		"lotus", "sunset", "split", "bind", "haven"
	],
	PUBG: [
		"ump45", "m416", "akm", "awm", "kar98k",
		"dp28", "scarl", "beryl", "vector", "tommygun",
		"winchester", "bluezone", "helmet", "vest", "backpack",
		"flaregun", "stungrenade", "smokegrenade", "fraggrenade", "motorglider",
		"snowbike", "pochinki", "school", "georgopol", "yasnaya polyana"
	],
	APEX: [
		"newcastle", "ballistic", "crypto", "vantage", "peacekeeper",
		"wingman", "r301", "flatline", "kraber", "mastiff",
		"sentinel", "devotion", "havoc", "hemlok", "alternator",
		"prowler", "respawn beacon", "jump tower", "replicator", "knockdown shield",
		"worlds edge", "olympus", "storm point", "kings canyon", "broken moon"
	],
	OVW: [
		"dva", "soldier 76", "doomfist", "junkrat", "zarya",
		"echo", "baptiste", "mauga", "junker queen", "wrecking ball",
		"lifeweaver", "hanamura", "ilios", "eichenwalde", "numbani",
		"rialto", "nepal", "lijiang tower", "watchpoint gibraltar", "blizzard world",
		"kings row", "busan", "havana", "dorado", "midtown"
	],
	"450": [
		{ word: "andromeda galaxy", definition: "A large spiral galaxy near the Milky Way." },
		{ word: "milky way", definition: "The galaxy that contains the solar system." },
		{ word: "light year", definition: "The distance light travels in one year." },
		{ word: "event horizon", definition: "The boundary beyond which nothing escapes a black hole.", extraThemes: [ "160" ] },
		{ word: "main sequence", definition: "The long stable phase of stellar evolution." },
		{ word: "solar flare", definition: "A sudden burst of radiation from the sun." },
		{ word: "sunspot", definition: "A darker and cooler region on the sun's surface." },
		{ word: "magnetar", definition: "A neutron star with an extremely strong magnetic field.", extraThemes: [ "160" ] },
		{ word: "protostar", definition: "A young star still forming from collapsing gas." },
		{ word: "accretion disk", definition: "A rotating disk of matter falling onto a massive object.", extraThemes: [ "160" ] },
		{ word: "albedo", definition: "The fraction of light or radiation a surface reflects." },
		{ word: "kuiper belt", definition: "A region of icy bodies beyond Neptune." },
		{ word: "oort cloud", definition: "A distant cloud of icy bodies surrounding the solar system." },
		{ word: "dwarf planet", definition: "A round world that has not cleared its orbital neighborhood." },
		{ word: "comet", definition: "An icy body that develops a glowing tail near the sun." },
		{ word: "retrograde", definition: "Appearing to move backward relative to the stars." },
		{ word: "transit", definition: "The passage of one body across the face of another." },
		{ word: "occultation", definition: "An event in which one object hides another from view." },
		{ word: "celestial sphere", definition: "An imaginary sphere used to map the sky." },
		{ word: "astrobiology", definition: "The study of life in the universe." },
		{ word: "heliocentrism", definition: "The model placing the sun at the center of planetary motion." },
		{ word: "geocentrism", definition: "The model placing Earth at the center of the cosmos." },
		{ word: "galactic cluster", definition: "A large grouping of galaxies held together by gravity." },
		{ word: "tidal force", definition: "A gravitational effect caused by differing pull across a body.", extraThemes: [ "160" ] },
		{ word: "barycenter", definition: "The shared center of mass around which bodies orbit." },
		{ word: "planetary nebula", definition: "A glowing shell of gas expelled by a dying star." },
		{ word: "open cluster", definition: "A loose group of stars formed from one cloud." },
		{ word: "globular cluster", definition: "A dense spherical collection of very old stars." },
		{ word: "redshift", definition: "The shift of light toward longer wavelengths from recession.", extraThemes: [ "160" ] },
		{ word: "blueshift", definition: "The shift of light toward shorter wavelengths from approach.", extraThemes: [ "160" ] }
	],
	"160": [
		{ word: "mass", definition: "The amount of matter in an object." },
		{ word: "force", definition: "An interaction that changes motion." },
		{ word: "torque", definition: "The turning effect of a force." },
		{ word: "impulse", definition: "A force acting over a time interval." },
		{ word: "wavelength", definition: "The distance between matching points on a wave." },
		{ word: "frequency", definition: "The number of wave cycles per unit time." },
		{ word: "amplitude", definition: "The maximum displacement of a wave or oscillation." },
		{ word: "voltage", definition: "Electric potential difference between two points." },
		{ word: "current", definition: "The flow rate of electric charge." },
		{ word: "capacitance", definition: "The ability to store electric charge." },
		{ word: "inductance", definition: "The property of opposing changes in current." },
		{ word: "refraction", definition: "The bending of a wave entering a new medium." },
		{ word: "polarization", definition: "The orientation pattern of a transverse wave." },
		{ word: "buoyancy", definition: "The upward force exerted by a fluid." },
		{ word: "viscosity", definition: "The resistance of a fluid to flow." },
		{ word: "work", definition: "Energy transferred when a force moves something." },
		{ word: "power", definition: "The rate of doing work or transferring energy." },
		{ word: "energy", definition: "The capacity to do work or cause change." },
		{ word: "kinetic energy", definition: "Energy due to motion." },
		{ word: "potential energy", definition: "Stored energy due to position or configuration." },
		{ word: "angular momentum", definition: "The rotational counterpart of linear momentum." },
		{ word: "plasma", definition: "An ionized state of matter." },
		{ word: "quark", definition: "A fundamental particle that forms hadrons." },
		{ word: "lepton", definition: "A fundamental particle not built from quarks." },
		{ word: "boson", definition: "A particle that carries force or shares quantum states." },
		{ word: "fermion", definition: "A particle that obeys the Pauli exclusion principle." },
		{ word: "isotope", definition: "An atom variant with a different neutron count." },
		{ word: "half life", definition: "The time needed for half of a radioactive sample to decay." },
		{ word: "nuclear fusion", definition: "The joining of nuclei to release energy." },
		{ word: "nuclear fission", definition: "The splitting of a nucleus to release energy." }
	],
	"490": [
		{ word: "binary tree", definition: "A tree structure where each node has at most two children." },
		{ word: "linked list", definition: "A linear structure made of connected nodes." },
		{ word: "stack", definition: "A collection that adds and removes from one end." },
		{ word: "queue", definition: "A collection that removes items in insertion order." },
		{ word: "graph", definition: "A structure of vertices connected by edges.", extraThemes: [ "240" ] },
		{ word: "hash table", definition: "A structure that maps keys to values using hashing." },
		{ word: "object oriented", definition: "A style of programming based on objects and classes." },
		{ word: "inheritance", definition: "A class relationship that reuses behavior from another class." },
		{ word: "polymorphism", definition: "A feature allowing one interface to support many forms." },
		{ word: "encapsulation", definition: "Bundling data and behavior inside a single unit." },
		{ word: "latency", definition: "The delay before a response begins." },
		{ word: "throughput", definition: "The amount of work completed in a period of time." },
		{ word: "bandwidth", definition: "The amount of data that can be transmitted over time." },
		{ word: "packet", definition: "A unit of data sent across a network." },
		{ word: "router", definition: "A device that forwards packets between networks." },
		{ word: "firewall", definition: "A system that filters network traffic by rule." },
		{ word: "load balancer", definition: "A component that spreads work across servers." },
		{ word: "application programming interface", definition: "A defined way for software components to interact." },
		{ word: "framework", definition: "A reusable platform for building software." },
		{ word: "library", definition: "A reusable collection of software code." },
		{ word: "garbage collection", definition: "Automatic recovery of unused program memory." },
		{ word: "deadlock", definition: "A state where processes wait forever on one another." },
		{ word: "mutex", definition: "A lock that grants exclusive access to a resource." },
		{ word: "semaphore", definition: "A signaling mechanism for coordinating concurrent tasks." },
		{ word: "container", definition: "A lightweight isolated environment for software." },
		{ word: "docker", definition: "A platform for building and running containers." },
		{ word: "kubernetes", definition: "A system for orchestrating containerized applications." },
		{ word: "runtime", definition: "The environment where a program executes." },
		{ word: "query language", definition: "A language used to retrieve or manipulate stored data." },
		{ word: "version control", definition: "A system for tracking changes to files and code." }
	],
	"240": [
		{ word: "prime number", definition: "A number divisible only by one and itself." },
		{ word: "composite number", definition: "A number with more than two positive divisors." },
		{ word: "rational number", definition: "A number expressible as a ratio of integers." },
		{ word: "irrational number", definition: "A number that cannot be written as a ratio of integers." },
		{ word: "complex number", definition: "A number with real and imaginary parts." },
		{ word: "imaginary unit", definition: "The number whose square equals negative one." },
		{ word: "limit", definition: "The value a function approaches near a point." },
		{ word: "series", definition: "The sum of the terms of a sequence." },
		{ word: "tensor", definition: "A multilinear mathematical object generalizing scalars and vectors." },
		{ word: "scalar", definition: "A quantity with magnitude but no direction." },
		{ word: "modulus", definition: "A value used as a divisor in modular arithmetic." },
		{ word: "quotient", definition: "The result of division." },
		{ word: "remainder", definition: "The part left after division." },
		{ word: "permutation", definition: "An arrangement of objects in order." },
		{ word: "combination", definition: "A selection of objects without regard to order." },
		{ word: "partition", definition: "A way of splitting a set or integer into parts." },
		{ word: "fibonacci sequence", definition: "A sequence where each term is the sum of the previous two." },
		{ word: "golden ratio", definition: "A famous proportion often denoted by phi." },
		{ word: "pascals triangle", definition: "A triangular array of binomial coefficients." },
		{ word: "ellipse", definition: "A conic section shaped like a stretched circle." },
		{ word: "parabola", definition: "A conic section formed by points equidistant from a focus and line." },
		{ word: "hyperbola", definition: "A conic section with two separated branches." },
		{ word: "fractal", definition: "A figure showing self-similar detail at different scales." },
		{ word: "determinant", definition: "A scalar value derived from a square matrix." },
		{ word: "vector space", definition: "A set closed under vector addition and scalar multiplication." },
		{ word: "inner product", definition: "A rule for measuring angles and lengths in a vector space." },
		{ word: "proof by induction", definition: "A proof method that establishes a base case and step." },
		{ word: "number theory", definition: "The branch of mathematics devoted to integers." },
		{ word: "graph theory", definition: "The study of graphs made of vertices and edges." },
		{ word: "measure theory", definition: "The branch of mathematics that formalizes size and integration." }
	],
	DSCI: [
		{ word: "confusion matrix", definition: "A table summarizing prediction outcomes by class." },
		{ word: "precision", definition: "The share of predicted positives that are correct." },
		{ word: "recall", definition: "The share of actual positives that are found." },
		{ word: "f1 score", definition: "A harmonic mean of precision and recall." },
		{ word: "roc curve", definition: "A curve comparing true positive and false positive rates." },
		{ word: "decision tree", definition: "A model that splits data by learned rules." },
		{ word: "random forest", definition: "An ensemble of decision trees." },
		{ word: "gradient boosting", definition: "An ensemble method that builds models stage by stage." },
		{ word: "naive bayes", definition: "A probabilistic classifier with strong independence assumptions." },
		{ word: "support vector machine", definition: "A classifier that seeks a maximum-margin boundary." },
		{ word: "principal component analysis", definition: "A method for reducing dimensionality by rotating features." },
		{ word: "correlation", definition: "A measure of how strongly variables vary together." },
		{ word: "covariance", definition: "A measure of joint variability between variables." },
		{ word: "bootstrap", definition: "A resampling method used to estimate uncertainty." },
		{ word: "etl", definition: "A workflow for extracting, transforming, and loading data." },
		{ word: "data warehouse", definition: "A central store designed for analytics." },
		{ word: "feature selection", definition: "The choice of which variables to keep in a model." },
		{ word: "label encoding", definition: "The conversion of categories into integer labels." },
		{ word: "one hot encoding", definition: "The conversion of categories into binary indicator columns." },
		{ word: "tokenization", definition: "The splitting of text into smaller units." },
		{ word: "stemming", definition: "The reduction of words to simplified stems." },
		{ word: "lemmatization", definition: "The reduction of words to dictionary forms." },
		{ word: "forecasting", definition: "The prediction of future values from past data." },
		{ word: "backtesting", definition: "The evaluation of a model on historical data." },
		{ word: "hyperparameter", definition: "A model setting chosen before training." },
		{ word: "normalization", definition: "The scaling of values into a common range." },
		{ word: "standardization", definition: "The scaling of values by mean and spread." },
		{ word: "anomaly detection", definition: "The identification of unusual patterns in data." },
		{ word: "class imbalance", definition: "A problem in which some labels are much rarer than others." },
		{ word: "dimensionality reduction", definition: "The compression of data into fewer informative variables." }
	],
	"150": [
		{ word: "the divine comedy", definition: "A major Italian poem about the soul's journey through the afterlife." },
		{ word: "the canterbury tales", definition: "A medieval collection of stories told by pilgrims." },
		{ word: "the metamorphosis", definition: "A novella about alienation and transformation." },
		{ word: "the stranger", definition: "A novel exploring absurdity and moral detachment." },
		{ word: "ulysses", definition: "A modernist novel famous for stylistic invention." },
		{ word: "the trial", definition: "A Kafka novel about accusation and inaccessible authority." },
		{ word: "the sound and the fury", definition: "A Faulkner novel about memory and a declining family." },
		{ word: "the grapes of wrath", definition: "A Steinbeck novel about migration and hardship in the Depression." },
		{ word: "to kill a mockingbird", definition: "A Pulitzer-winning novel about justice and childhood in the American South." },
		{ word: "invisible man", definition: "A landmark novel about identity and racial invisibility." },
		{ word: "things fall apart", definition: "A classic novel about colonial disruption in Igbo society." },
		{ word: "the name of the rose", definition: "A historical mystery novel set in a medieval monastery." },
		{ word: "the remains of the day", definition: "A Booker-winning novel about duty, memory, and regret." },
		{ word: "disgrace", definition: "A Booker-winning novel set in post-apartheid South Africa." },
		{ word: "the road", definition: "A bleak novel about survival after civilizational collapse." },
		{ word: "the god of small things", definition: "A Booker-winning novel about family, caste, and memory." },
		{ word: "wolf hall", definition: "A Booker-winning novel about Thomas Cromwell and Tudor politics." },
		{ word: "the vegetarian", definition: "A Booker-winning novel about refusal, violence, and desire." },
		{ word: "the luminaries", definition: "A Booker-winning novel built around a gold-rush mystery." },
		{ word: "the plague", definition: "A novel about epidemic, fear, and moral responsibility." },
		{ word: "candide", definition: "A satirical novella attacking philosophical optimism." },
		{ word: "paradise lost", definition: "An epic poem about rebellion, fall, and redemption." },
		{ word: "the republic", definition: "A classical dialogue on justice, politics, and education." },
		{ word: "the brothers karamazov", definition: "A major novel about faith, freedom, and family conflict." },
		{ word: "war and peace", definition: "A vast historical novel about Russia during the Napoleonic era." },
		{ word: "crime and punishment", definition: "A novel about guilt, conscience, and moral suffering." },
		{ word: "one hundred years of solitude", definition: "A famous novel of family history and magical realism." },
		{ word: "a tale of two cities", definition: "A historical novel set around the French Revolution." },
		{ word: "the sun also rises", definition: "A modern novel about disillusioned expatriates after war." },
		{ word: "a farewell to arms", definition: "A war novel about love and loss." }
	],
	"30": [
		{ word: "bull market", definition: "A sustained period of rising asset prices." },
		{ word: "bear market", definition: "A sustained period of falling asset prices." },
		{ word: "interest rate", definition: "The price paid for borrowing money." },
		{ word: "exchange rate", definition: "The price of one currency in terms of another." },
		{ word: "opportunity cost", definition: "The value of the best alternative forgone." },
		{ word: "marginal cost", definition: "The added cost of producing one more unit." },
		{ word: "marginal revenue", definition: "The added revenue from selling one more unit." },
		{ word: "supply shock", definition: "A sudden change in the availability or cost of supply." },
		{ word: "demand shock", definition: "A sudden change in demand conditions." },
		{ word: "quantitative easing", definition: "A central-bank policy of buying assets to inject liquidity." },
		{ word: "fiscal policy", definition: "Government tax and spending policy used to influence the economy." },
		{ word: "monetary policy", definition: "Central-bank policy used to influence money and credit." },
		{ word: "consumer surplus", definition: "The gap between what buyers pay and what they were willing to pay." },
		{ word: "producer surplus", definition: "The gap between market price and the minimum sellers would accept." },
		{ word: "price ceiling", definition: "A legal maximum price." },
		{ word: "price floor", definition: "A legal minimum price." },
		{ word: "stagflation", definition: "High inflation combined with weak growth and unemployment." },
		{ word: "austerity", definition: "A policy of reducing public spending to control deficits." },
		{ word: "privatization", definition: "The transfer of state assets or services to private ownership." },
		{ word: "nationalization", definition: "The transfer of private assets into state ownership." },
		{ word: "arbitrage", definition: "The profit from price differences across markets." },
		{ word: "depreciation", definition: "A decline in the value of an asset or currency." },
		{ word: "appreciation", definition: "A rise in the value of an asset or currency." },
		{ word: "unemployment", definition: "The state of being able to work but unable to find a job." },
		{ word: "productivity", definition: "Output produced per unit of input." },
		{ word: "elasticity", definition: "The responsiveness of one variable to changes in another." },
		{ word: "balance of trade", definition: "The value difference between exports and imports." },
		{ word: "current account", definition: "A record of trade and income flows with the rest of the world." },
		{ word: "capital gain", definition: "Profit from selling an asset above its purchase price." },
		{ word: "labor market", definition: "The market in which workers and employers meet." }
	],
	"310": [
		{ word: "morpheme", definition: "The smallest meaning-bearing unit in language." },
		{ word: "allomorph", definition: "A variant form of the same morpheme." },
		{ word: "phoneme", definition: "A sound category that distinguishes meaning." },
		{ word: "allophone", definition: "A phonetic variant of a phoneme." },
		{ word: "syllable", definition: "A sound unit centered on a vowel-like nucleus." },
		{ word: "lexicon", definition: "The vocabulary of a language or speaker." },
		{ word: "syntax tree", definition: "A diagram of grammatical structure." },
		{ word: "predicate", definition: "The part of a clause that says something about the subject." },
		{ word: "ergative", definition: "A grammatical alignment marking subjects differently in transitive and intransitive clauses." },
		{ word: "absolutive", definition: "A grammatical role paired with ergative alignment." },
		{ word: "phonotactics", definition: "The pattern rules governing sound combinations." },
		{ word: "diacritic", definition: "A written mark added to a letter." },
		{ word: "orthography", definition: "The conventional spelling system of a language." },
		{ word: "pragmatics", definition: "The study of meaning in context." },
		{ word: "etymology", definition: "The study of word origins and historical development." },
		{ word: "code switching", definition: "Alternating between languages or varieties in discourse." },
		{ word: "diglossia", definition: "The coexistence of high and low language varieties." },
		{ word: "idiolect", definition: "The distinctive language habits of one individual." },
		{ word: "sociolinguistics", definition: "The study of language in social context." },
		{ word: "psycholinguistics", definition: "The study of language processing in the mind." },
		{ word: "consonant", definition: "A speech sound made with notable constriction." },
		{ word: "vowel", definition: "A speech sound made without major constriction." },
		{ word: "stress", definition: "Relative prominence assigned to a syllable." },
		{ word: "tone", definition: "Pitch used to distinguish word meaning." },
		{ word: "aspect", definition: "A grammatical category describing temporal structure." },
		{ word: "tense", definition: "A grammatical category locating an event in time." },
		{ word: "mood", definition: "A grammatical category expressing attitude or modality." },
		{ word: "voice", definition: "A grammatical pattern relating actions to participants." },
		{ word: "grammar", definition: "The structural system of a language." },
		{ word: "loanword", definition: "A word borrowed from another language." }
	],
	"350": [
		{ word: "powerplay", definition: "A period when one side has a player advantage." },
		{ word: "triple double", definition: "A basketball game with double digits in three categories." },
		{ word: "double double", definition: "A basketball game with double digits in two categories." },
		{ word: "clean sheet", definition: "A game in which a team allows no goals." },
		{ word: "red card", definition: "A penalty that sends a player off in soccer." },
		{ word: "yellow card", definition: "A formal warning in soccer." },
		{ word: "corner kick", definition: "A restart awarded when the defense last touches the ball over the goal line." },
		{ word: "free kick", definition: "A restart awarded after certain fouls." },
		{ word: "penalty shootout", definition: "A tie-break sequence of penalty kicks." },
		{ word: "grand slam", definition: "A major title or, in baseball, a four-run home run." },
		{ word: "pole position", definition: "The leading starting spot in motorsport." },
		{ word: "three pointer", definition: "A basketball shot worth three points." },
		{ word: "pick and roll", definition: "A basketball action involving a screen and cut." },
		{ word: "bodycheck", definition: "A forceful defensive hit in hockey." },
		{ word: "power forward", definition: "A basketball position combining size and mobility." },
		{ word: "point guard", definition: "A basketball player who organizes the offense." },
		{ word: "shortstop", definition: "An infield position in baseball." },
		{ word: "endzone", definition: "The scoring area at the end of an American football field." },
		{ word: "scrimmage", definition: "A practice game or a line-of-play restart in football." },
		{ word: "faceoff", definition: "A restart in hockey or lacrosse where opponents contest possession." },
		{ word: "shot put", definition: "A track-and-field event that throws a heavy ball." },
		{ word: "heptathlon", definition: "A combined event of seven track-and-field contests." },
		{ word: "decathlon", definition: "A combined event of ten track-and-field contests." },
		{ word: "stroke play", definition: "A golf format scored by total strokes." },
		{ word: "match play", definition: "A golf format scored by holes won." },
		{ word: "power serve", definition: "A fast and aggressive serve in racket sports." },
		{ word: "drop shot", definition: "A softly hit shot that lands short." },
		{ word: "counterattack", definition: "A quick attack launched after winning possession." },
		{ word: "checkmate", definition: "A position in chess where the king cannot escape capture." },
		{ word: "playmaker", definition: "A player known for creating scoring chances." }
	],
	"1001": [
		{ word: "south korea", definition: "A country in East Asia on the southern Korean Peninsula.", extraThemes: [ "e15" ] },
		{ word: "north korea", definition: "A country in East Asia on the northern Korean Peninsula.", extraThemes: [ "e15" ] },
		{ word: "new zealand", definition: "An island country in the southwestern Pacific Ocean.", extraThemes: [ "e15" ] },
		{ word: "south africa", definition: "A country at the southern tip of Africa.", extraThemes: [ "e15" ] },
		{ word: "saudi arabia", definition: "A large country on the Arabian Peninsula.", extraThemes: [ "e15" ] },
		{ word: "united arab emirates", definition: "A federation of emirates on the Arabian Gulf.", extraThemes: [ "e15" ] },
		{ word: "costa rica", definition: "A Central American country between Nicaragua and Panama.", extraThemes: [ "e15" ] },
		{ word: "el salvador", definition: "A country in Central America on the Pacific coast.", extraThemes: [ "e15" ] },
		{ word: "dominican republic", definition: "A Caribbean country occupying most of Hispaniola.", extraThemes: [ "e15" ] },
		{ word: "czech republic", definition: "A central European country also known as Czechia.", extraThemes: [ "e15" ] },
		{ word: "sri lanka", definition: "An island country south of India.", extraThemes: [ "e15" ] },
		{ word: "papua new guinea", definition: "A country on the eastern half of New Guinea.", extraThemes: [ "e15" ] },
		{ word: "north macedonia", definition: "A Balkan country in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "bosnia and herzegovina", definition: "A Balkan country in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "south sudan", definition: "A country in East-Central Africa that became independent in 2011.", extraThemes: [ "e15" ] },
		{ word: "san marino", definition: "A microstate surrounded by Italy.", extraThemes: [ "e15" ] },
		{ word: "sierra leone", definition: "A West African country on the Atlantic coast.", extraThemes: [ "e15" ] },
		{ word: "united states", definition: "A country in North America composed of fifty states.", extraThemes: [ "e15" ] },
		{ word: "united kingdom", definition: "A country made up of England, Scotland, Wales, and Northern Ireland.", extraThemes: [ "e15" ] },
		{ word: "colombia", definition: "A South American country with coasts on two seas.", extraThemes: [ "e15" ] },
		{ word: "chile", definition: "A long narrow country on South America's Pacific coast.", extraThemes: [ "e15" ] },
		{ word: "peru", definition: "A South American country home to Machu Picchu.", extraThemes: [ "e15" ] },
		{ word: "morocco", definition: "A North African country facing the Atlantic and Mediterranean.", extraThemes: [ "e15" ] },
		{ word: "algeria", definition: "The largest country in Africa by land area.", extraThemes: [ "e15" ] },
		{ word: "tunisia", definition: "A North African country on the Mediterranean coast.", extraThemes: [ "e15" ] },
		{ word: "thailand", definition: "A Southeast Asian country long known for Bangkok and tourism.", extraThemes: [ "e15" ] },
		{ word: "vietnam", definition: "A Southeast Asian country on the South China Sea.", extraThemes: [ "e15" ] },
		{ word: "indonesia", definition: "A large archipelagic country in Southeast Asia.", extraThemes: [ "e15" ] },
		{ word: "philippines", definition: "An island country in Southeast Asia.", extraThemes: [ "e15" ] },
		{ word: "pakistan", definition: "A South Asian country west of India.", extraThemes: [ "e15" ] },
		{ word: "bangladesh", definition: "A densely populated South Asian country on the Bay of Bengal.", extraThemes: [ "e15" ] },
		{ word: "kazakhstan", definition: "A large Central Asian country extending into eastern Europe.", extraThemes: [ "e15" ] },
		{ word: "ukraine", definition: "An Eastern European country on the Black Sea.", extraThemes: [ "e15" ] },
		{ word: "switzerland", definition: "A central European country known for the Alps and neutrality.", extraThemes: [ "e15" ] }
	],
	NBAP: [
		{ word: "paul pierce", definition: "Paul Pierce debuted in 1998 and became Boston's Finals MVP in 2008." },
		{ word: "ray allen", definition: "Ray Allen debuted in 1996 and became one of the greatest shooters in NBA history." },
		{ word: "vince carter", definition: "Vince Carter debuted in 1998 and became famous for scoring and dunking longevity." },
		{ word: "tracy mcgrady", definition: "Tracy McGrady debuted in 1997 and became a multiple-time scoring champion." },
		{ word: "carmelo anthony", definition: "Carmelo Anthony debuted in 2003 and became one of the defining scorers of his era." },
		{ word: "dwight howard", definition: "Dwight Howard debuted in 2004 and won three straight Defensive Player of the Year awards." },
		{ word: "tony parker", definition: "Tony Parker debuted in 2001 and won four NBA titles with San Antonio." },
		{ word: "manu ginobili", definition: "Manu Ginobili debuted in 2002 and became a Hall of Fame guard for the Spurs." },
		{ word: "chauncey billups", definition: "Chauncey Billups debuted in 1997 and led Detroit to the 2004 championship." },
		{ word: "ben wallace", definition: "Ben Wallace debuted in 1996 and won four Defensive Player of the Year awards." },
		{ word: "pau gasol", definition: "Pau Gasol debuted in 2001 and won two NBA titles with the Lakers." },
		{ word: "marc gasol", definition: "Marc Gasol debuted in 2008 and became a Defensive Player of the Year and champion." },
		{ word: "yao ming", definition: "Yao Ming debuted in 2002 and became a global basketball icon for Houston." },
		{ word: "derrick rose", definition: "Derrick Rose debuted in 2008 and became the youngest MVP in NBA history." },
		{ word: "blake griffin", definition: "Blake Griffin debuted in 2010 and became a multi-time All-Star forward." },
		{ word: "klay thompson", definition: "Klay Thompson debuted in 2011 and won multiple titles with Golden State." },
		{ word: "draymond green", definition: "Draymond Green debuted in 2012 and became the defensive core of Golden State's dynasty." },
		{ word: "jaylen brown", definition: "Jaylen Brown debuted in 2016 and became an All-NBA wing for Boston." },
		{ word: "donovan mitchell", definition: "Donovan Mitchell debuted in 2017 and quickly became a high-volume scoring guard." },
		{ word: "trae young", definition: "Trae Young debuted in 2018 and became one of the NBA's most creative offensive guards." },
		{ word: "domantas sabonis", definition: "Domantas Sabonis debuted in 2016 and became a multiple-time All-Star big man." },
		{ word: "demar derozan", definition: "DeMar DeRozan debuted in 2009 and became known for elite mid-range scoring." },
		{ word: "jrue holiday", definition: "Jrue Holiday debuted in 2009 and became one of the league's best two-way guards." },
		{ word: "khris middleton", definition: "Khris Middleton debuted in 2012 and helped Milwaukee win the 2021 title." },
		{ word: "bam adebayo", definition: "Bam Adebayo debuted in 2017 and became Miami's defensive anchor at center." },
		{ word: "pascal siakam", definition: "Pascal Siakam debuted in 2016 and won the 2019 championship with Toronto." },
		{ word: "rudy gobert", definition: "Rudy Gobert debuted in 2013 and won multiple Defensive Player of the Year awards." },
		{ word: "karl anthony towns", definition: "Karl-Anthony Towns debuted in 2015 and became a star scoring center." },
		{ word: "paolo banchero", definition: "Paolo Banchero debuted in 2022 and won Rookie of the Year in 2023." },
		{ word: "cade cunningham", definition: "Cade Cunningham debuted in 2021 and became Detroit's lead playmaking guard." },
		{ word: "chet holmgren", definition: "Chet Holmgren debuted in 2023 and quickly became a two-way frontcourt talent." },
		{ word: "alperen sengun", definition: "Alperen Sengun debuted in 2021 and became Houston's skilled hub center." },
		{ word: "deaaron fox", definition: "De'Aaron Fox debuted in 2017 and became Sacramento's franchise guard." },
		{ word: "bradley beal", definition: "Bradley Beal debuted in 2012 and became one of Washington's top scorers." },
		{ word: "shawn kemp", definition: "Shawn Kemp debuted in 1989 and became a dominant power finisher in the 1990s." }
	],
	SOCP: [
		{ word: "zlatan ibrahimovic", definition: "Zlatan Ibrahimovic debuted in 1999 and became one of the most decorated strikers of his era." },
		{ word: "didier drogba", definition: "Didier Drogba debuted in 1998 and became a legendary Chelsea and Ivory Coast striker." },
		{ word: "frank lampard", definition: "Frank Lampard debuted in 1996 and became one of the highest-scoring midfielders ever." },
		{ word: "steven gerrard", definition: "Steven Gerrard debuted in 1998 and captained Liverpool through a famous Champions League comeback." },
		{ word: "paolo maldini", definition: "Paolo Maldini debuted in 1985 and became one of football's great defenders." },
		{ word: "roberto baggio", definition: "Roberto Baggio debuted in 1982 and became one of Italy's most gifted forwards." },
		{ word: "franz beckenbauer", definition: "Franz Beckenbauer debuted in 1964 and helped redefine the libero role." },
		{ word: "george best", definition: "George Best debuted in 1963 and became a legendary winger for Manchester United." },
		{ word: "ruud gullit", definition: "Ruud Gullit debuted in 1979 and starred for club and country in the 1980s." },
		{ word: "marco van basten", definition: "Marco van Basten debuted in 1981 and won three Ballon d'Or awards." },
		{ word: "roberto carlos", definition: "Roberto Carlos debuted in 1991 and became one of football's most famous attacking fullbacks." },
		{ word: "rivaldo", definition: "Rivaldo debuted in 1991 and won the 1999 Ballon d'Or." },
		{ word: "cafu", definition: "Cafu debuted in 1989 and won two World Cups with Brazil." },
		{ word: "sergio busquets", definition: "Sergio Busquets debuted in 2008 and became a key holding midfielder for Barcelona and Spain." },
		{ word: "thomas muller", definition: "Thomas Muller debuted in 2008 and became one of Germany's most productive attackers." },
		{ word: "antoine griezmann", definition: "Antoine Griezmann debuted in 2009 and became one of France's defining forwards." },
		{ word: "harry kane", definition: "Harry Kane debuted in 2011 and became England's record scorer." },
		{ word: "son heung min", definition: "Son Heung-min debuted in 2010 and became one of Asia's most recognized footballers." },
		{ word: "bukayo saka", definition: "Bukayo Saka debuted in 2018 and became a leading winger for Arsenal and England." },
		{ word: "vinicius junior", definition: "Vinicius Junior debuted in 2017 and became a Champions League-winning winger for Real Madrid." },
		{ word: "jude bellingham", definition: "Jude Bellingham debuted in 2019 and quickly became one of Europe's top midfielders." },
		{ word: "pedri", definition: "Pedri debuted in 2019 and became a key creative midfielder for Barcelona and Spain." },
		{ word: "rodri", definition: "Rodri debuted in 2015 and became an elite controlling midfielder for club and country." },
		{ word: "bernardo silva", definition: "Bernardo Silva debuted in 2013 and became a versatile playmaker for Portugal and Manchester City." },
		{ word: "thibaut courtois", definition: "Thibaut Courtois debuted in 2009 and became one of Europe's top goalkeepers." },
		{ word: "jan oblak", definition: "Jan Oblak debuted in 2009 and became a renowned goalkeeper for Atletico Madrid." },
		{ word: "riyad mahrez", definition: "Riyad Mahrez debuted in 2009 and starred in Leicester City's title-winning season." },
		{ word: "sadio mane", definition: "Sadio Mane debuted in 2011 and became a Champions League and league winner with Liverpool." },
		{ word: "dani alves", definition: "Dani Alves debuted in 2001 and became one of the most decorated fullbacks ever." },
		{ word: "gianluigi donnarumma", definition: "Gianluigi Donnarumma debuted in 2015 and became Italy's Euro-winning goalkeeper." },
		{ word: "luis figo", definition: "Luis Figo debuted in 1989 and won the 2000 Ballon d'Or." },
		{ word: "patrick vieira", definition: "Patrick Vieira debuted in 1994 and became a dominant midfielder for club and country." },
		{ word: "ruud van nistelrooy", definition: "Ruud van Nistelrooy debuted in 1993 and became one of Europe's top finishers." },
		{ word: "fernando torres", definition: "Fernando Torres debuted in 2001 and won major titles for Spain and club sides." },
		{ word: "alan shearer", definition: "Alan Shearer debuted in 1988 and remains the Premier League's all-time leading scorer." }
	],
	"410": [
		{ word: "agnosticism", definition: "The view that ultimate reality is unknown or unknowable." },
		{ word: "atheism", definition: "The absence or rejection of belief in gods." },
		{ word: "ritual", definition: "A repeated ceremonial action with religious meaning." },
		{ word: "clergy", definition: "The body of ordained religious leaders." },
		{ word: "heresy", definition: "Belief judged contrary to accepted doctrine." },
		{ word: "orthodoxy", definition: "Accepted belief or established doctrine." },
		{ word: "mysticism", definition: "Religious pursuit of direct experience of the divine." },
		{ word: "cathedral", definition: "The principal church of a bishop's district." },
		{ word: "mosque", definition: "A place of worship in Islam." },
		{ word: "synagogue", definition: "A place of worship and assembly in Judaism." },
		{ word: "temple", definition: "A building dedicated to religious worship." },
		{ word: "monastery", definition: "A community and residence for monks or nuns." },
		{ word: "chaplain", definition: "A clergy member serving an institution or group." },
		{ word: "sermon", definition: "A religious discourse delivered to an audience." },
		{ word: "parable", definition: "A short teaching story with moral or spiritual meaning." },
		{ word: "prophet", definition: "A person regarded as a messenger of divine truth." },
		{ word: "revelation", definition: "Disclosure of sacred truth by divine means." },
		{ word: "covenant", definition: "A solemn religious agreement or promise." },
		{ word: "afterlife", definition: "Existence believed to continue after death." },
		{ word: "salvation", definition: "Deliverance from sin or suffering." },
		{ word: "atonement", definition: "Reconciliation made for wrongdoing or sin." },
		{ word: "fasting", definition: "Abstaining from food or other things for religious reasons." },
		{ word: "meditation", definition: "Focused contemplation used in spiritual practice." },
		{ word: "rabbi", definition: "A Jewish religious teacher or leader." },
		{ word: "imam", definition: "A Muslim prayer leader or scholar." },
		{ word: "pastor", definition: "A Christian minister responsible for a congregation." },
		{ word: "bishop", definition: "A senior Christian cleric overseeing churches." },
		{ word: "martyr", definition: "A person who dies for a religious cause or belief." },
		{ word: "saint", definition: "A person regarded as holy or exceptionally virtuous." },
		{ word: "pilgrim", definition: "A person who travels for religious devotion." }
	],
	"100": [
		{ word: "tank", definition: "A heavily armored fighting vehicle with a large gun." },
		{ word: "sniper", definition: "A shooter trained for accurate long-range fire." },
		{ word: "drone", definition: "An unmanned aircraft used for surveillance or attack." },
		{ word: "missile", definition: "A guided weapon propelled toward a target." },
		{ word: "radar", definition: "A system that detects objects using radio waves." },
		{ word: "sonar", definition: "A system that detects underwater objects using sound." },
		{ word: "corvette", definition: "A small warship used for patrol and escort." },
		{ word: "bomber", definition: "A military aircraft built to drop bombs." },
		{ word: "fighter", definition: "A military aircraft designed for air combat." },
		{ word: "fortification", definition: "A defensive military structure or strengthening." },
		{ word: "airstrike", definition: "An attack delivered by aircraft." },
		{ word: "salvo", definition: "A simultaneous discharge of several weapons." },
		{ word: "flank", definition: "The side of a military formation." },
		{ word: "encirclement", definition: "A maneuver that surrounds an opposing force." },
		{ word: "barrage", definition: "Heavy continuous artillery fire." },
		{ word: "warfare", definition: "The conduct of war or armed conflict." },
		{ word: "trench", definition: "A long defensive ditch used by troops." },
		{ word: "foxhole", definition: "A small defensive pit dug for cover." },
		{ word: "munition", definition: "A military explosive or projectile." },
		{ word: "special forces", definition: "Elite military units trained for specialized missions." },
		{ word: "peacekeeping", definition: "Military operations meant to preserve or restore peace." },
		{ word: "deterrence", definition: "The prevention of attack by threat of response." },
		{ word: "warhead", definition: "The explosive or destructive part of a missile." },
		{ word: "rifleman", definition: "An infantry soldier armed primarily with a rifle." },
		{ word: "counteroffensive", definition: "An attack launched in response to an enemy advance." },
		{ word: "armored division", definition: "A large formation centered on tanks and other armored vehicles." },
		{ word: "rules of engagement", definition: "Directives defining when military force may be used." },
		{ word: "frontline", definition: "The forward edge of a military battle area." },
		{ word: "naval blockade", definition: "The use of warships to prevent access to a coast or port." },
		{ word: "air superiority", definition: "Control of the sky over a battle area." }
	],
	"370": [
		{ word: "hematology", definition: "The study of blood and blood disorders." },
		{ word: "dermatology", definition: "The branch of medicine dealing with skin." },
		{ word: "nephrology", definition: "The branch of medicine dealing with kidneys." },
		{ word: "pulmonology", definition: "The branch of medicine dealing with lungs and breathing." },
		{ word: "endocrinology", definition: "The branch of medicine dealing with hormones." },
		{ word: "orthopedics", definition: "The branch of medicine dealing with bones and joints." },
		{ word: "psychiatry", definition: "The branch of medicine dealing with mental disorders." },
		{ word: "embolism", definition: "A blockage caused by material traveling through the bloodstream." },
		{ word: "ischemia", definition: "A shortage of blood supply to tissue." },
		{ word: "tachycardia", definition: "An abnormally fast heart rate." },
		{ word: "bradycardia", definition: "An abnormally slow heart rate." },
		{ word: "hypertension", definition: "Persistently high blood pressure." },
		{ word: "hypotension", definition: "Abnormally low blood pressure." },
		{ word: "diabetes", definition: "A disease involving problems with blood sugar regulation." },
		{ word: "arthritis", definition: "Inflammation of joints causing pain and stiffness." },
		{ word: "asthma", definition: "A condition causing inflamed and narrowed airways." },
		{ word: "pneumonia", definition: "Infection that inflames the air sacs of the lungs." },
		{ word: "chemotherapy", definition: "Drug treatment used especially against cancer." },
		{ word: "radiotherapy", definition: "Treatment using controlled radiation." },
		{ word: "homeostasis", definition: "The maintenance of stable internal conditions in the body." },
		{ word: "microbiology", definition: "The study of microscopic organisms." },
		{ word: "histology", definition: "The study of tissues under the microscope." },
		{ word: "cytology", definition: "The study of cells." },
		{ word: "analgesic", definition: "A drug used to relieve pain." },
		{ word: "antiviral", definition: "A drug or agent used against viruses." },
		{ word: "antifungal", definition: "A drug or agent used against fungal infection." },
		{ word: "resuscitation", definition: "Measures used to restore breathing or circulation." },
		{ word: "defibrillator", definition: "A device that uses electric shock to restore heart rhythm." },
		{ word: "stethoscope", definition: "An instrument used to listen to internal body sounds." },
		{ word: "scalpel", definition: "A small sharp knife used in surgery." }
	]
};
