module.exports = {
	MINC: [
		"wooden pickaxe", "stone pickaxe", "iron pickaxe", "diamond pickaxe", "netherite sword",
		"slime", "magma cube", "hoglin", "zoglin", "strider",
		"drowned", "husk", "pillager", "ravager", "evoker",
		"vindicator", "allay", "armadillo", "woodland mansion", "ancient city"
	],
	STA: [
		"siege tank", "medivac", "thor", "marauder", "reaper",
		"bunker", "stimpack", "yamato cannon", "baneling nest", "roach warren",
		"overseer", "brood lord", "corruptor", "infestor", "colossus",
		"immortal", "phoenix", "void ray", "dark shrine", "warp gate"
	],
	POK: [
		"raichu", "pichu", "togepi", "cyndaquil", "totodile",
		"bayleef", "typhlosion", "feraligatr", "milotic", "aggron",
		"absol", "staraptor", "luxray", "roserade", "togekiss",
		"serperior", "emboar", "samurott", "talonflame", "toxtricity"
	],
	FORT: [
		"tilted towers", "dusty divot", "loot lake", "flush factory", "port a fort",
		"shopping cart", "quadcrasher", "battle pass", "victory royale", "reboot card",
		"island flip", "the seven", "imagined order", "slurpy swamp", "coney crossroads",
		"brutal bastion", "faulty splits", "rift to go", "cozy campfire", "legendary scar"
	],
	VALO: [
		"clutch", "ace", "eco round", "full buy", "half buy",
		"spike plant", "spike defuse", "orbital strike", "null command", "boombot",
		"trailblazer", "aftershock", "flashpoint", "wallbang", "one tap",
		"heaven", "hookah", "showers", "market", "mid doors"
	],
	PUBG: [
		"paramo", "rondo", "mp5k", "qbz", "qbu",
		"mk12", "mini14", "sks", "vss", "pp bizon",
		"m24", "groza", "aug", "ace32", "self revive kit",
		"blue chip tower", "emergency parachute", "san martin", "bootcamp", "pecado"
	],
	APEX: [
		"mad maggie", "catalyst", "conduit", "survey beacon", "ring console",
		"ultimate accelerant", "shield battery", "shield cell", "med kit", "syringe",
		"fragment east", "fragment west", "skull town", "labs", "estates",
		"barometer", "bonsai plaza", "care package", "mobile respawn beacon", "gold helmet"
	],
	OVW: [
		"sigma", "kiriko", "ramattra", "pharah", "sombra",
		"mei", "symmetra", "orisa", "reinhardt", "winston",
		"route 66", "hollywood", "oasis", "paraiso", "junkertown",
		"samoa", "suravasa", "runasapi", "new queen street", "esperanca"
	],
	"450": [
		{ word: "horsehead nebula", definition: "A dark nebula silhouetted against glowing gas." },
		{ word: "orion nebula", definition: "A bright nearby nebula where stars are forming." },
		{ word: "alpha centauri", definition: "The nearest stellar system to the sun." },
		{ word: "proxima centauri", definition: "The closest known star to the sun." },
		{ word: "supermassive black hole", definition: "A giant black hole found at a galaxy center.", extraThemes: [ "160" ] },
		{ word: "gravitational lens", definition: "The bending of light by massive objects.", extraThemes: [ "160" ] },
		{ word: "solar corona", definition: "The hot outer atmosphere of the sun." },
		{ word: "solar prominence", definition: "A large loop of glowing gas rising from the sun." },
		{ word: "libration", definition: "A slight apparent oscillation that reveals more of the moon." },
		{ word: "sidereal year", definition: "The orbital period measured relative to the stars." },
		{ word: "meteor shower", definition: "A burst of meteors appearing from one region of sky." },
		{ word: "rayleigh criterion", definition: "A rule used to estimate optical resolving power.", extraThemes: [ "160" ] },
		{ word: "escape velocity", definition: "The speed needed to break free from gravity.", extraThemes: [ "160" ] },
		{ word: "synchronous orbit", definition: "An orbit whose period matches the body's rotation." },
		{ word: "geostationary orbit", definition: "A circular orbit fixed above one point on Earth." },
		{ word: "roche limit", definition: "The distance within which tidal forces break a satellite apart.", extraThemes: [ "160" ] },
		{ word: "doppler effect", definition: "A frequency shift caused by relative motion.", extraThemes: [ "160" ] },
		{ word: "apparent magnitude", definition: "A measure of how bright an object looks from Earth." },
		{ word: "absolute magnitude", definition: "A measure of intrinsic brightness at a standard distance." },
		{ word: "solar system", definition: "The sun and all objects gravitationally bound to it." }
	],
	"160": [
		{ word: "wave number", definition: "The spatial frequency of a wave." },
		{ word: "angular frequency", definition: "A rate of oscillation measured in radians per second." },
		{ word: "free fall", definition: "Motion under gravity alone." },
		{ word: "terminal velocity", definition: "The constant speed reached when drag balances weight." },
		{ word: "young modulus", definition: "A measure of stiffness in a material." },
		{ word: "shear stress", definition: "Stress produced by forces acting parallel to a surface." },
		{ word: "strain energy", definition: "Energy stored in a deformed body." },
		{ word: "blackbody radiation", definition: "Thermal radiation emitted by an ideal absorber." },
		{ word: "specific heat", definition: "Heat required to raise unit mass by one degree." },
		{ word: "latent heat", definition: "Heat absorbed or released during a phase change." },
		{ word: "lorentz force", definition: "The force on a charge moving in electric and magnetic fields." },
		{ word: "maxwell equations", definition: "The equations governing classical electromagnetism." },
		{ word: "electrostatics", definition: "The study of charges at rest." },
		{ word: "fluid mechanics", definition: "The study of liquids and gases in motion and rest." },
		{ word: "bernoulli principle", definition: "A relation linking pressure and speed in fluid flow." },
		{ word: "reynolds number", definition: "A value used to predict flow behavior in fluids." },
		{ word: "laminar flow", definition: "Smooth fluid motion in parallel layers." },
		{ word: "turbulent flow", definition: "Chaotic fluid motion with mixing and eddies." },
		{ word: "photoelectric effect", definition: "Electron emission caused by light.", extraThemes: [ "490" ] },
		{ word: "doppler shift", definition: "The frequency change caused by relative motion." }
	],
	"490": [
		{ word: "red black tree", definition: "A self balancing binary search tree." },
		{ word: "binary search tree", definition: "A tree ordered so left values are smaller and right values larger." },
		{ word: "adjacency matrix", definition: "A matrix representation of graph connections.", extraThemes: [ "240" ] },
		{ word: "adjacency list", definition: "A graph representation that stores neighbors per vertex.", extraThemes: [ "240" ] },
		{ word: "minimum spanning tree", definition: "A smallest weight set of edges connecting a graph.", extraThemes: [ "240" ] },
		{ word: "shortest path", definition: "The minimum cost route between nodes.", extraThemes: [ "240" ] },
		{ word: "binary heap", definition: "A heap structure commonly used for priority queues." },
		{ word: "merge sort", definition: "A divide and conquer sorting algorithm.", extraThemes: [ "240" ] },
		{ word: "quick sort", definition: "A sorting algorithm based on partitioning." },
		{ word: "breadth first traversal", definition: "Level by level exploration of a structure." },
		{ word: "depth first traversal", definition: "Branch by branch exploration of a structure." },
		{ word: "relational database", definition: "A database organized around tables and relations." },
		{ word: "database index", definition: "A structure that speeds up lookup in stored data." },
		{ word: "transaction log", definition: "A record of database changes used for recovery." },
		{ word: "dead code", definition: "Code that never executes or has no effect." },
		{ word: "race condition", definition: "A bug caused by timing dependent access to shared state." },
		{ word: "dependency injection", definition: "A design technique that supplies dependencies from outside." },
		{ word: "continuous integration", definition: "Frequent automated testing and building of code." },
		{ word: "continuous deployment", definition: "Automatic release of validated software changes." },
		{ word: "distributed database", definition: "A database spread across multiple machines." }
	],
	"240": [
		{ word: "binomial theorem", definition: "A formula for expanding powers of a sum." },
		{ word: "law of large numbers", definition: "A theorem about averages stabilizing with more trials.", extraThemes: [ "DSCI" ] },
		{ word: "central limit theorem", definition: "A theorem stating sums often approach a normal distribution.", extraThemes: [ "DSCI" ] },
		{ word: "bayes theorem", definition: "A rule for updating probabilities with new evidence.", extraThemes: [ "DSCI" ] },
		{ word: "euler formula", definition: "A famous relation connecting complex exponentials and trigonometry." },
		{ word: "taylor series", definition: "A power series used to approximate functions." },
		{ word: "laplace transform", definition: "An integral transform used to solve equations." },
		{ word: "fourier series", definition: "A representation of functions as sums of sinusoids." },
		{ word: "vector field", definition: "An assignment of a vector to every point in space." },
		{ word: "scalar field", definition: "An assignment of a scalar to every point in space." },
		{ word: "gradient descent", definition: "An iterative method that moves toward smaller values.", extraThemes: [ "DSCI" ] },
		{ word: "simplex method", definition: "An algorithm for solving linear programming problems." },
		{ word: "convex function", definition: "A function whose line segments lie above its graph." },
		{ word: "eigenvector", definition: "A vector whose direction is unchanged by a transformation." },
		{ word: "orthogonal matrix", definition: "A matrix whose transpose equals its inverse." },
		{ word: "inner product space", definition: "A vector space equipped with an inner product." },
		{ word: "ring theory", definition: "The study of algebraic structures with addition and multiplication." },
		{ word: "group theory", definition: "The study of sets with a single associative operation." },
		{ word: "compactness", definition: "A property that generalizes finiteness in topology." },
		{ word: "monte carlo method", definition: "A computational method using repeated random sampling.", extraThemes: [ "DSCI" ] }
	],
	DSCI: [
		{ word: "calibration", definition: "The alignment of predicted probabilities with observed outcomes." },
		{ word: "feature importance", definition: "A measure of how much variables influence a model." },
		{ word: "train test split", definition: "A partition of data into development and evaluation sets." },
		{ word: "validation set", definition: "A held out set used while choosing models." },
		{ word: "test set", definition: "A held out set used for final evaluation." },
		{ word: "precision recall curve", definition: "A curve comparing precision and recall across thresholds." },
		{ word: "stratified sampling", definition: "Sampling that preserves group proportions." },
		{ word: "imbalanced dataset", definition: "A dataset in which some classes are much rarer than others." },
		{ word: "feature drift", definition: "A change in variable behavior over time." },
		{ word: "concept drift", definition: "A change in the relationship between inputs and targets." },
		{ word: "exploratory data analysis", definition: "Initial investigation of data through summary and visualization." },
		{ word: "dimensionality curse", definition: "Problems caused by data becoming sparse in high dimensions." },
		{ word: "nearest neighbor", definition: "A method based on similarity to nearby examples." },
		{ word: "k means", definition: "A clustering method that partitions data into k groups." },
		{ word: "hierarchical clustering", definition: "Clustering that builds nested groups." },
		{ word: "topic modeling", definition: "Methods for finding hidden themes in documents." },
		{ word: "word embedding", definition: "A dense numeric representation of word meaning." },
		{ word: "time series", definition: "Data recorded in temporal order." },
		{ word: "surrogate model", definition: "A simpler model used to approximate a complex process." },
		{ word: "data governance", definition: "Policies and practices for managing data quality and use." }
	],
	"150": [
		{ word: "the iliad", definition: "An ancient Greek epic about wrath and war at Troy." },
		{ word: "the odyssey", definition: "An ancient Greek epic about Odysseus returning home." },
		{ word: "the aeneid", definition: "A Roman epic following Aeneas after Troy." },
		{ word: "the faerie queene", definition: "A long allegorical poem about virtue and chivalry." },
		{ word: "the red and the black", definition: "A novel about ambition and class in France." },
		{ word: "fathers and sons", definition: "A novel about generational conflict and nihilism." },
		{ word: "dead souls", definition: "A satirical Russian novel about greed and corruption." },
		{ word: "the castle", definition: "A novel about authority and exclusion." },
		{ word: "in search of lost time", definition: "A major modernist novel cycle about memory and society." },
		{ word: "doctor zhivago", definition: "A novel of love and upheaval in Russia." },
		{ word: "the goldfinch", definition: "A Pulitzer-winning novel about grief, art, and obsession." },
		{ word: "the overstory", definition: "A Pulitzer-winning novel linking many lives through trees." },
		{ word: "a portrait of the artist as a young man", definition: "A modernist novel about artistic awakening." },
		{ word: "the waste land", definition: "A landmark modernist poem of fragmentation and cultural ruin." },
		{ word: "song of solomon", definition: "A celebrated novel about family history and identity." },
		{ word: "the age of innocence", definition: "A Pulitzer-winning novel of manners and desire." },
		{ word: "all the light we cannot see", definition: "A Pulitzer-winning novel set during the Second World War." },
		{ word: "the narrow road to the deep north", definition: "A Booker-winning novel about war and memory." },
		{ word: "midnights children", definition: "A Booker-winning novel tied to Indian independence." },
		{ word: "season of migration to the north", definition: "A major postcolonial novel about return and displacement." }
	],
	"30": [
		{ word: "consumer price index", definition: "A measure of average price change over time." },
		{ word: "gross domestic product", definition: "The total value of final goods and services produced." },
		{ word: "gross national income", definition: "The total income earned by residents of a country." },
		{ word: "comparative advantage", definition: "The ability to produce at lower opportunity cost." },
		{ word: "opportunity cost", definition: "The value of the best alternative given up." },
		{ word: "market equilibrium", definition: "The price and quantity where supply equals demand." },
		{ word: "price ceiling", definition: "A legal maximum price." },
		{ word: "price floor", definition: "A legal minimum price." },
		{ word: "purchasing power", definition: "The amount of goods and services money can buy." },
		{ word: "current account", definition: "A record of trade and income flows with the world." },
		{ word: "trade deficit", definition: "A condition in which imports exceed exports." },
		{ word: "trade surplus", definition: "A condition in which exports exceed imports." },
		{ word: "capital market", definition: "A market for long term financing instruments." },
		{ word: "money supply", definition: "The total amount of money circulating in an economy." },
		{ word: "consumer surplus", definition: "The gap between willingness to pay and actual price." },
		{ word: "producer surplus", definition: "The gap between market price and minimum acceptable price." },
		{ word: "progressive tax", definition: "A tax whose rate rises with income." },
		{ word: "regressive tax", definition: "A tax that takes a larger share from lower incomes." },
		{ word: "marginal utility", definition: "The extra satisfaction from one more unit consumed." },
		{ word: "purchasing parity", definition: "A comparison of currencies based on buying power." }
	],
	"310": [
		{ word: "comparative linguistics", definition: "The study of relationships among languages." },
		{ word: "historical linguistics", definition: "The study of how languages change over time." },
		{ word: "language family", definition: "A group of related languages descending from a common source." },
		{ word: "word order", definition: "The arrangement of core sentence elements." },
		{ word: "case marking", definition: "Grammatical marking of a noun's role." },
		{ word: "agreement", definition: "Grammatical matching between words." },
		{ word: "voice", definition: "A grammatical system that changes argument prominence." },
		{ word: "aspect", definition: "A grammatical category describing the flow of an event." },
		{ word: "tense", definition: "A grammatical category locating an event in time." },
		{ word: "modality", definition: "A linguistic category expressing possibility or necessity." },
		{ word: "grammaticalization", definition: "The process by which words develop grammatical functions." },
		{ word: "pidgin", definition: "A simplified contact language with limited functions." },
		{ word: "creole", definition: "A fully developed language that arises from contact." },
		{ word: "loanword", definition: "A word borrowed from another language." },
		{ word: "calque", definition: "A borrowed expression translated piece by piece." },
		{ word: "semantic shift", definition: "A change in a word's meaning over time." },
		{ word: "minimal pair", definition: "Two words differing in only one sound." },
		{ word: "speech act", definition: "An utterance treated as an action." },
		{ word: "deixis", definition: "Language whose meaning depends on context like here or now." },
		{ word: "information structure", definition: "The organization of old and new information in discourse." }
	],
	"350": [
		{ word: "counterattack", definition: "A rapid attack launched after winning the ball." },
		{ word: "clean sheet", definition: "A game in which a team allows no goals." },
		{ word: "power play", definition: "A numerical advantage caused by an opponent penalty." },
		{ word: "penalty area", definition: "The box in front of goal where certain fouls cause a penalty." },
		{ word: "yellow card", definition: "A formal caution shown by a referee." },
		{ word: "red card", definition: "A dismissal shown by a referee." },
		{ word: "match point", definition: "The point that can end a match in racket sports." },
		{ word: "break point", definition: "A point that can win a game against the server." },
		{ word: "pole position", definition: "The front starting spot in motor racing." },
		{ word: "fast break", definition: "A quick attacking move before the defense is set." },
		{ word: "double double", definition: "A basketball stat line with double digits in two categories." },
		{ word: "triple double", definition: "A basketball stat line with double digits in three categories." },
		{ word: "alley oop", definition: "A play where one player catches and scores a lob pass." },
		{ word: "pick and roll", definition: "A two player basketball action using a screen and cut." },
		{ word: "home run derby", definition: "A baseball hitting contest focused on home runs." },
		{ word: "sudden death", definition: "A format in which the next score ends play." },
		{ word: "time out", definition: "A stoppage requested by a team or official." },
		{ word: "world cup", definition: "A top international championship tournament." },
		{ word: "champions league", definition: "A major European club competition in soccer." },
		{ word: "grand slam", definition: "Either the four major tennis tournaments or winning all of them." }
	],
	"1001": [
		{ word: "south korea", definition: "A country on the southern half of the Korean Peninsula.", extraThemes: [ "e15" ] },
		{ word: "north korea", definition: "A country on the northern half of the Korean Peninsula.", extraThemes: [ "e15" ] },
		{ word: "north macedonia", definition: "A Balkan country in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "saudi arabia", definition: "A large Middle Eastern country on the Arabian Peninsula.", extraThemes: [ "e15" ] },
		{ word: "united arab emirates", definition: "A federation of seven emirates in the Gulf region.", extraThemes: [ "e15" ] },
		{ word: "new zealand", definition: "An island country in the southwestern Pacific.", extraThemes: [ "e15" ] },
		{ word: "south africa", definition: "A country at the southern tip of Africa.", extraThemes: [ "e15" ] },
		{ word: "costa rica", definition: "A Central American country known for biodiversity.", extraThemes: [ "e15" ] },
		{ word: "dominican republic", definition: "A Caribbean country sharing Hispaniola.", extraThemes: [ "e15" ] },
		{ word: "czech republic", definition: "A central European country also known as Czechia.", extraThemes: [ "e15" ] },
		{ word: "papua new guinea", definition: "A country occupying the eastern half of New Guinea.", extraThemes: [ "e15" ] },
		{ word: "sri lanka", definition: "An island country south of India.", extraThemes: [ "e15" ] },
		{ word: "saint lucia", definition: "A Caribbean island nation in the eastern Caribbean.", extraThemes: [ "e15" ] },
		{ word: "el salvador", definition: "A Central American country on the Pacific coast.", extraThemes: [ "e15" ] },
		{ word: "cote divoire", definition: "A West African country also known as Ivory Coast.", extraThemes: [ "e15" ] },
		{ word: "sierra leone", definition: "A West African country on the Atlantic coast.", extraThemes: [ "e15" ] },
		{ word: "the philippines", definition: "A Southeast Asian archipelago nation.", extraThemes: [ "e15" ] },
		{ word: "the netherlands", definition: "A European country known for lowlands and canals.", extraThemes: [ "e15" ] },
		{ word: "bosnia and herzegovina", definition: "A Balkan country in southeastern Europe.", extraThemes: [ "e15" ] },
		{ word: "trinidad and tobago", definition: "A Caribbean twin island nation.", extraThemes: [ "e15" ] }
	],
	NBAP: [
		{ word: "tim duncan", definition: "Tim Duncan debuted in 1997 and won five NBA titles with San Antonio." },
		{ word: "kevin garnett", definition: "Kevin Garnett debuted in 1995 and won MVP and an NBA championship." },
		{ word: "dirk nowitzki", definition: "Dirk Nowitzki debuted in 1998 and led Dallas to the 2011 title." },
		{ word: "steve nash", definition: "Steve Nash debuted in 1996 and won back to back MVP awards." },
		{ word: "allen iverson", definition: "Allen Iverson debuted in 1996 and won the 2001 NBA MVP." },
		{ word: "vince carter", definition: "Vince Carter debuted in 1998 and became famous for scoring and dunking longevity." },
		{ word: "chris bosh", definition: "Chris Bosh debuted in 2003 and won two NBA titles with Miami." },
		{ word: "pau gasol", definition: "Pau Gasol debuted in 2001 and won two NBA titles with the Lakers." },
		{ word: "tony parker", definition: "Tony Parker debuted in 2001 and won four NBA titles with San Antonio." },
		{ word: "manu ginobili", definition: "Manu Ginobili debuted in 2002 and became a Hall of Fame sixth man and champion." },
		{ word: "yao ming", definition: "Yao Ming debuted in 2002 and became a global star at center for Houston." },
		{ word: "tracy mcgrady", definition: "Tracy McGrady debuted in 1997 and became a scoring champion and star wing." },
		{ word: "chauncey billups", definition: "Chauncey Billups debuted in 1997 and led Detroit to the 2004 title." },
		{ word: "reggie miller", definition: "Reggie Miller debuted in 1987 and became one of the great playoff shooters." },
		{ word: "klay thompson", definition: "Klay Thompson debuted in 2011 and won four NBA titles with Golden State." },
		{ word: "draymond green", definition: "Draymond Green debuted in 2012 and became the defensive anchor of Golden State's dynasty." },
		{ word: "donovan mitchell", definition: "Donovan Mitchell debuted in 2017 and became a prolific scoring guard." },
		{ word: "jaylen brown", definition: "Jaylen Brown debuted in 2016 and became a two way star for Boston." },
		{ word: "bradley beal", definition: "Bradley Beal debuted in 2012 and became a multiple time All Star scorer." },
		{ word: "demar derozan", definition: "DeMar DeRozan debuted in 2009 and became a multiple time All Star wing scorer." }
	],
	SOCP: [
		{ word: "zinedine zidane", definition: "Zinedine Zidane debuted in 1989 and won the 1998 World Cup with France." },
		{ word: "thierry henry", definition: "Thierry Henry debuted in 1994 and became Arsenal's record scorer." },
		{ word: "sergio ramos", definition: "Sergio Ramos debuted in 2004 and won the World Cup and multiple Champions League titles." },
		{ word: "luka modric", definition: "Luka Modric debuted in 2003 and won the 2018 Ballon d'Or." },
		{ word: "karim benzema", definition: "Karim Benzema debuted in 2004 and won the 2022 Ballon d'Or." },
		{ word: "xavi", definition: "Xavi debuted in 1998 and became Barcelona's midfield organizer for a golden era." },
		{ word: "andres iniesta", definition: "Andres Iniesta debuted in 2002 and scored Spain's 2010 World Cup winning goal." },
		{ word: "wayne rooney", definition: "Wayne Rooney debuted in 2002 and became Manchester United's record scorer." },
		{ word: "frank lampard", definition: "Frank Lampard debuted in 1995 and became Chelsea's highest scoring midfielder." },
		{ word: "steven gerrard", definition: "Steven Gerrard debuted in 1998 and became Liverpool's iconic captain." },
		{ word: "paolo maldini", definition: "Paolo Maldini debuted in 1985 and became one of football's greatest defenders." },
		{ word: "andrea pirlo", definition: "Andrea Pirlo debuted in 1995 and became renowned for passing and control." },
		{ word: "gianluigi buffon", definition: "Gianluigi Buffon debuted in 1995 and became one of football's greatest goalkeepers." },
		{ word: "manuel neuer", definition: "Manuel Neuer debuted in 2005 and redefined sweeping goalkeeper play." },
		{ word: "didier drogba", definition: "Didier Drogba debuted in 1998 and became a big match striker for Chelsea." },
		{ word: "ronaldinho", definition: "Ronaldinho debuted in 1998 and became famous for flair and a Ballon d'Or." },
		{ word: "mohamed salah", definition: "Mohamed Salah debuted in 2010 and became Liverpool's modern scoring icon." },
		{ word: "virgil van dijk", definition: "Virgil van Dijk debuted in 2011 and anchored Liverpool's defense to major titles." },
		{ word: "kevin de bruyne", definition: "Kevin De Bruyne debuted in 2008 and became one of the best attacking midfielders of his era." },
		{ word: "robert lewandowski", definition: "Robert Lewandowski debuted in 2006 and became one of Europe's most reliable scorers." }
	],
	"410": [
		{ word: "monotheism", definition: "Belief in one God." },
		{ word: "polytheism", definition: "Belief in many gods." },
		{ word: "atheism", definition: "The absence of belief in gods." },
		{ word: "agnosticism", definition: "The view that ultimate religious certainty is unknown or unknowable." },
		{ word: "clergy", definition: "Religious leaders who conduct worship and rites." },
		{ word: "monastery", definition: "A religious community building for monks or nuns." },
		{ word: "abbey", definition: "A monastery or convent under an abbot or abbess." },
		{ word: "cathedral", definition: "A principal church containing a bishop's seat." },
		{ word: "mosque", definition: "A Muslim place of worship." },
		{ word: "synagogue", definition: "A Jewish place of worship and assembly." },
		{ word: "temple", definition: "A building devoted to religious worship." },
		{ word: "baptism", definition: "A ritual of initiation using water in Christianity." },
		{ word: "resurrection", definition: "Rising from death to life again." },
		{ word: "reformation", definition: "A major movement of religious reform in Western Christianity." },
		{ word: "protestantism", definition: "The branch of Christianity that emerged from the Reformation." },
		{ word: "catholicism", definition: "The branch of Christianity centered on the Catholic Church." },
		{ word: "orthodoxy", definition: "The branch of Christianity associated with Eastern Orthodox churches." },
		{ word: "buddhism", definition: "A religion and philosophy centered on the teachings of the Buddha." },
		{ word: "hinduism", definition: "A major religious tradition originating in the Indian subcontinent." },
		{ word: "islam", definition: "A monotheistic religion centered on the Quran and Muhammad." }
	],
	"100": [
		{ word: "battalion", definition: "A military unit made of several companies." },
		{ word: "brigade", definition: "A military formation larger than a regiment and smaller than a division." },
		{ word: "division", definition: "A large military formation made of brigades." },
		{ word: "platoon", definition: "A military unit smaller than a company." },
		{ word: "squadron", definition: "A military unit used in air or cavalry forces." },
		{ word: "flank", definition: "The side of a military formation." },
		{ word: "artillery barrage", definition: "Sustained shelling from artillery weapons." },
		{ word: "armored warfare", definition: "Combat centered on tanks and armored vehicles." },
		{ word: "air superiority", definition: "Control of the air over a battlefield." },
		{ word: "amphibious assault", definition: "A military attack launched from sea onto land." },
		{ word: "supply line", definition: "The route that carries troops and material to the front." },
		{ word: "rules of engagement", definition: "Directives governing when forces may use force." },
		{ word: "special forces", definition: "Military units trained for specialized missions." },
		{ word: "reconnaissance", definition: "The military observation of terrain and enemy activity." },
		{ word: "deterrence", definition: "The strategy of discouraging attack through threatened response." },
		{ word: "ballistic missile", definition: "A missile that follows a ballistic trajectory." },
		{ word: "aircraft carrier", definition: "A warship designed to deploy aircraft at sea." },
		{ word: "stealth bomber", definition: "A bomber designed to reduce detection." },
		{ word: "drone strike", definition: "An attack carried out by an unmanned aircraft." },
		{ word: "ceasefire", definition: "An agreement to stop fighting temporarily or permanently." }
	],
	"370": [
		{ word: "radiology", definition: "The medical use of imaging to diagnose and treat disease." },
		{ word: "pathology", definition: "The study of disease and its effects." },
		{ word: "cardiology", definition: "The branch of medicine dealing with the heart." },
		{ word: "neurology", definition: "The branch of medicine dealing with the nervous system." },
		{ word: "dermatology", definition: "The branch of medicine dealing with the skin." },
		{ word: "anesthesiology", definition: "The branch of medicine dealing with anesthesia and perioperative care." },
		{ word: "orthopedics", definition: "The branch of medicine dealing with bones and joints." },
		{ word: "oncology", definition: "The branch of medicine dealing with cancer." },
		{ word: "hematology", definition: "The branch of medicine dealing with blood disorders." },
		{ word: "nephrology", definition: "The branch of medicine dealing with the kidneys." },
		{ word: "pulmonology", definition: "The branch of medicine dealing with the lungs and breathing." },
		{ word: "gastroenterology", definition: "The branch of medicine dealing with the digestive system." },
		{ word: "endocrinology", definition: "The branch of medicine dealing with hormones and glands." },
		{ word: "rheumatology", definition: "The branch of medicine dealing with joints and autoimmune disorders." },
		{ word: "epidemiology", definition: "The study of disease patterns in populations." },
		{ word: "biopsy", definition: "The removal of tissue for medical examination." },
		{ word: "ultrasound", definition: "Imaging that uses high frequency sound waves." },
		{ word: "ct scan", definition: "Imaging that uses X rays to create cross sectional views." },
		{ word: "mri scan", definition: "Imaging that uses magnetic fields and radio waves." },
		{ word: "blood pressure", definition: "The force of blood against vessel walls." }
	]
};
